#!/usr/bin/env python3
"""Part 5 — 12 casino review pages.
Casinos: Rolla, SpinSaga, SpinPals, SpinDoo, Stackr, GoldRushCity,
         MegaFrenzy, JackpotRabbit, ScarletSands, LuckyBitsVegas, Cazino, Sweepshark
"""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from seo_all_reviews import build, BASE

CASINOS = [

# 1. ROLLA
dict(
 slug='rolla', name='Rolla', score='4.0', tier='High Tier',
 site_url='https://rolla.com', affiliate='https://affiliates.routy.app/route/114425?affId=3353&ts=5005447',
 parent='Skillzz Gaming Group (Malta)', launch='2021', age='18+',
 daily='$1 SC/day', welcome='Welcome package on signup',
 min_redeem='$10 SC (gift cards) / $50 SC (cash)', payout_speed='2–5 business days',
 games='700+', r_games='4.0', r_bonus='4.0', r_payout='4.0',
 restricted=['ID','WA','MT','MI','NV'],
 title='Rolla Casino Review 2026 — Legit? $1 Daily SC, Low Minimums, Canada OK',
 meta_desc='Rolla review 2026: 4.0/5. Skillzz Gaming Group. $1 SC daily, $10 gift card minimum, 700+ games, Canada + Ontario eligible. Is Rolla legit? Full honest review.',
 keywords='rolla casino review, is rolla legit, rolla daily bonus, rolla payout, rolla canada sweepstakes 2026',
 h1='Rolla Review 2026: <span class="highlight">$1 Daily SC & Canada Eligible</span>',
 verdict='Rolla earns High Tier status through consistent value: $1 SC daily, a $10 gift card minimum, and one of the few sweepstakes casinos available in both Canada and Ontario. The Skillzz Gaming Group infrastructure is proven. Not flashy, but reliable — a solid addition to any daily rotation on both sides of the border.',
 schema_body='Rolla is a Skillzz Gaming Group sweepstakes casino offering $1 SC daily, $10 gift card minimum, 700+ games, and availability in Canada and Ontario.',
 what_is='<p>Rolla is operated by <strong>Skillzz Gaming Group</strong> (Malta) — the same established operator behind several routy-network sweepstakes casinos. Launched in 2021, Rolla has built a reputation as a <strong>reliable daily performer</strong> with one significant advantage over most competitors: <strong>Canada and Ontario eligibility</strong>.</p><p>For Canadian players, the sweepstakes casino landscape is limited. Rolla, alongside WOW Vegas, Crown Coins, McLuck, Pulsz, and a handful of others, accepts Canadian accounts — including Ontario, which is often excluded even from Canada-eligible platforms.</p><p>The platform delivers <strong>$1 SC daily</strong> on login — predictable and farmable — combined with a <strong>$10 gift card minimum</strong> that makes the first redemption accessible after only 10 qualifying logins.</p>',
 promo='<p>Rolla provides a <strong>welcome package</strong> for new accounts. The platform runs regular promotional events through the Skillzz network. The main daily value is the <strong>consistent $1 SC</strong> credited each login — steady, farmable earning without the randomness of other platforms.</p>',
 steps=['Visit <a href="https://affiliates.routy.app/route/114425?affId=3353&ts=5005447" target="_blank" rel="noopener">Rolla Casino</a> and create an account.','Verify your email to activate your account and welcome offer.','Log in daily to collect the $1 SC login bonus.','Explore the 700+ game library.','Reach $10 SC for a gift card or $50 SC for cash.'],
 pros=['$1 SC daily — predictable, farmable earning','$10 gift card minimum — accessible first redemption','Canada + Ontario eligible — rare in sweepstakes','Skillzz Gaming Group — Malta-licensed and proven','700+ game library with good variety','$50 cash minimum — below the $100 standard'],
 cons=['No VIP loyalty program','No cryptocurrency redemption option','Malta-licensed (not US-regulated)','Medium promotional frequency beyond daily SC','Limited live game selection'],
 games_detail='<p>Rolla offers <strong>700+ games</strong> from the Skillzz catalog, covering slots across all volatility levels, table game basics (blackjack, roulette), and specialty titles. The catalog is solid for a High Tier platform and performs well on mobile. Regular new additions from Skillzz software partners.</p>',
 bonus_detail='<p>Rolla\'s daily earning is built around the <strong>fixed $1 SC daily login bonus</strong> — no randomness, no variability. It credits every login reliably. The welcome package provides an entry boost, and the Skillzz promotional calendar adds seasonal value throughout the year.</p>',
 payout_detail='<p>Rolla offers the <strong>most accessible redemption structure</strong> in High Tier: <strong>$10 SC for gift cards</strong> and <strong>$50 SC for cash</strong>. Complete KYC identity verification before submitting. Processing takes <strong>2–5 business days</strong>.</p>',
 faqs=[
  ('Is Rolla Casino legit?','Yes. Rolla is operated by Skillzz Gaming Group (Malta) and has been running since 2021 with a consistent payout record.'),
  ('Is Rolla available in Canada?','Yes — Rolla accepts players from Canada, including Ontario. One of the few sweepstakes casinos with full CA/ON eligibility.'),
  ('What is the daily bonus at Rolla?','$1 SC per login — a fixed, predictable daily credit.'),
  ('What is the minimum payout at Rolla?','$10 SC for gift cards and $50 SC for cash redemptions.'),
  ('Does Rolla have crypto payouts?','No. Gift card and cash redemptions only.'),
  ('Who operates Rolla Casino?','Skillzz Gaming Group, a Malta-based gaming operator.'),
 ]
),

# 2. SPINSAGA
dict(
 slug='spinsaga', name='SpinSaga', score='3.8', tier='Mid Tier',
 site_url='https://www.spinsagacasino.com', affiliate='https://play.spinsagacasino.com/?ref=29904&campaign=referFriend',
 parent='SpinSaga Ltd (Cyprus)', launch='2023', age='18+',
 daily='Daily SC login bonus', welcome='Welcome package for new players',
 min_redeem='$50 SC (cash)', payout_speed='3–7 business days',
 games='600+', r_games='3.8', r_bonus='3.8', r_payout='3.8',
 restricted=['ID','WA','MT','MI','NV','CT'],
 title='SpinSaga Casino Review 2026 — Legit? Daily Bonus, Payouts & Rating',
 meta_desc='SpinSaga review 2026: 3.8/5. Cyprus-licensed, $50 cash minimum, 600+ games, daily SC login bonus. Is SpinSaga legit? Full honest review for US sweepstakes players.',
 keywords='spinsaga casino review, is spinsaga legit, spinsaga daily bonus, spinsaga payout, spinsaga promo code 2026',
 h1='SpinSaga Review 2026: <span class="highlight">$50 Cash Floor & Solid Mid Tier Platform</span>',
 verdict='SpinSaga is a competent Mid Tier sweepstakes casino with a $50 cash minimum that makes payouts more accessible than most $100-floor competitors. The 600+ game library, daily SC login bonus, and consistent operator track record since 2023 make it a reliable addition to a multi-platform rotation.',
 schema_body='SpinSaga is a Cyprus-licensed sweepstakes casino with 600+ games, daily SC login bonus, and $50 cash minimum redemption.',
 what_is='<p>SpinSaga launched in 2023 as a <strong>Cyprus-licensed sweepstakes casino</strong> targeting US players. It has quickly established itself as a <strong>reliable Mid Tier performer</strong> — consistent daily SC bonuses, a straightforward platform, and a $50 cash minimum that reduces the barrier to first redemption.</p><p>The 600+ game library is solid for the Mid Tier, with a mix of slots, table games, and specialty titles. For multi-platform farmers, SpinSaga adds another reliable daily earning channel to the rotation without demanding high attention or complex bonus tracking.</p>',
 promo='<p>SpinSaga offers a <strong>welcome package</strong> for new registrations. The platform runs periodic promotions and seasonal events alongside the daily login SC bonus. Check the promotions page after registration for the current welcome offer details.</p>',
 steps=['Visit <a href="https://play.spinsagacasino.com/?ref=29904&campaign=referFriend" target="_blank" rel="noopener">SpinSaga Casino</a> and sign up.','Complete email verification to activate your account.','Claim your welcome offer from the promotions section.','Log in daily to collect your SC bonus.','Accumulate $50 SC for your first cash redemption.'],
 pros=['$50 cash minimum — lower than the $100 standard','600+ game library with solid slot selection','Daily SC login bonus — consistent farming','Cyprus-licensed legitimate operator','Clean, easy-to-navigate platform','Good fit for multi-platform rotation'],
 cons=['No VIP loyalty program','No gift card or crypto redemptions','Cyprus licensing less rigorous than US-regulated','Limited promotional calendar beyond daily SC','Canada not available'],
 games_detail='<p>SpinSaga offers <strong>600+ games</strong> covering slots (all volatility levels), table game basics, and specialty titles. The catalog is clean and mobile-optimized. Slot selection is the highlight, with new titles added regularly. Table games cover the essentials — blackjack, roulette, and poker variants.</p>',
 bonus_detail='<p>SpinSaga\'s daily login bonus provides a consistent SC credit each day. The welcome package front-loads value for new accounts. The promotional calendar supplements with seasonal events and periodic reload bonuses, though frequency is medium compared to High Tier platforms.</p>',
 payout_detail='<p>SpinSaga requires <strong>$50 SC</strong> minimum for cash redemption — below the industry-standard $100. Complete KYC identity verification in your account settings before submitting. Processing takes <strong>3–7 business days</strong>. No gift card or crypto options currently.</p>',
 faqs=[
  ('Is SpinSaga legit?','Yes. SpinSaga has been operating since 2023 with a consistent payout track record.'),
  ('What is the minimum payout at SpinSaga?','$50 SC for cash redemption — lower than most competitors at $100.'),
  ('What is the daily bonus at SpinSaga?','A daily SC login bonus — check the platform for current amounts.'),
  ('Does SpinSaga support crypto payouts?','No. Cash redemption only at $50 minimum.'),
  ('Is SpinSaga available in Canada?','No. US only.'),
  ('Who operates SpinSaga?','SpinSaga Ltd, a Cyprus-based gaming company.'),
 ]
),

# 3. SPINPALS
dict(
 slug='spinpals', name='SpinPals', score='3.7', tier='Mid Tier',
 site_url='https://www.spinpals.com', affiliate='https://www.spinpals.com/?referralcode=50405075-7105-4b67-b399-a16f9599a795',
 parent='SpinPals LLC', launch='2023', age='18+',
 daily='Daily SC login bonus', welcome='Welcome coins on signup',
 min_redeem='$100 SC (cash)', payout_speed='3–7 business days',
 games='500+', r_games='3.7', r_bonus='3.7', r_payout='3.7',
 restricted=['ID','WA','MT','MI','NV','CT'],
 title='SpinPals Casino Review 2026 — Legit? Daily Bonus, Payouts & Rating',
 meta_desc='SpinPals review 2026: 3.7/5. Newer US sweepstakes casino with 500+ games, daily SC bonus, referral rewards. Is SpinPals legit? Full honest review 2026.',
 keywords='spinpals casino review, is spinpals legit, spinpals daily bonus, spinpals payout, spinpals referral code 2026',
 h1='SpinPals Review 2026: <span class="highlight">Community-Focused Mid Tier Platform</span>',
 verdict='SpinPals is a newer Mid Tier sweepstakes casino with a referral-based community angle — active recruiting earns additional SC. The 500+ game library, daily SC login bonus, and referral program make it worth adding to a rotation, though the $100 cash minimum and no VIP or crypto options keep it below High Tier.',
 schema_body='SpinPals is a sweepstakes casino with 500+ games, daily SC login bonus, referral program, and $100 cash minimum redemption.',
 what_is='<p>SpinPals is a newer sweepstakes casino that differentiates itself with a <strong>referral and community model</strong>. The platform rewards players for inviting others — a secondary earning stream alongside the daily SC login bonus. This makes SpinPals particularly interesting for players with social followings or active sweepstakes communities.</p><p>The <strong>500+ game library</strong> covers the core sweepstakes experience, and the daily login bonus provides consistent earning. For multi-platform farmers, SpinPals adds a referral layer that most other casinos don\'t offer — and with a unique referral code baked into the signup link, tracking your recruits is straightforward.</p>',
 promo='<p>SpinPals provides <strong>welcome coins</strong> for new signups and an ongoing <strong>referral program</strong> that rewards you when your referred players stay active. The daily SC login bonus provides baseline earning. Check the promotions page for current offer details.</p>',
 steps=['Visit <a href="https://www.spinpals.com/?referralcode=50405075-7105-4b67-b399-a16f9599a795" target="_blank" rel="noopener">SpinPals</a> and register.','Complete email verification to receive your welcome coins.','Log in daily for the SC login bonus.','Share your own referral code to earn bonus SC from recruits.','Accumulate $100 SC for your first cash redemption.'],
 pros=['Referral program — extra earning for community-connected players','Daily SC login bonus — consistent earning','500+ game library','Welcome coins on signup','Community-friendly platform design','US-regulated operator'],
 cons=['$100 cash minimum — standard but not standout','No gift card or crypto redemption options','No VIP loyalty program','Shorter operational history','Canada not available','Limited promotional calendar beyond referrals and daily SC'],
 games_detail='<p>SpinPals offers <strong>500+ games</strong> spanning slots, basic table games, and specialty titles. The catalog focuses on quality over quantity with smooth mobile performance. Slot selection covers the main volatility ranges with regular new additions. Table games include blackjack, roulette, and poker basics.</p>',
 bonus_detail='<p>SpinPals provides two main bonus structures: the <strong>daily SC login bonus</strong> (consistent earning) and the <strong>referral program</strong> (additional SC when referred players are active). The combination gives engaged, social players more earning potential than a standard single-channel bonus.</p>',
 payout_detail='<p>SpinPals requires <strong>$100 SC</strong> minimum for cash redemption. Complete KYC identity verification before submitting your withdrawal request. Processing takes <strong>3–7 business days</strong>. No gift card or crypto options available.</p>',
 faqs=[
  ('Is SpinPals legit?','SpinPals is a legitimate newer sweepstakes casino with a verifiable referral program and consistent payout reports.'),
  ('Does SpinPals have a referral program?','Yes — you earn additional SC when players you refer stay active on the platform.'),
  ('What is the minimum payout at SpinPals?','$100 SC for cash redemption.'),
  ('What is the daily bonus at SpinPals?','A daily SC login bonus — check the platform for current amounts.'),
  ('Is SpinPals available in Canada?','No. US only.'),
  ('Does SpinPals support crypto payouts?','No. Cash redemption only.'),
 ]
),

# 4. SPINDOO
dict(
 slug='spindoo', name='SpinDoo', score='3.6', tier='Mid Tier',
 site_url='https://www.spindoo.us', affiliate='https://www.spindoo.us/?r=28402933',
 parent='SpinDoo Inc', launch='2024', age='18+',
 daily='Daily SC bonus', welcome='Welcome offer on signup',
 min_redeem='$100 SC (cash)', payout_speed='3–7 business days',
 games='400+', r_games='3.6', r_bonus='3.6', r_payout='3.6',
 restricted=['ID','WA','MT','MI','NV','CT'],
 title='SpinDoo Casino Review 2026 — Legit? Daily Bonus, Payouts & Rating',
 meta_desc='SpinDoo review 2026: 3.6/5. New US sweepstakes casino with 400+ games, daily SC bonus, $100 cash minimum. Is SpinDoo legit? Full honest review 2026.',
 keywords='spindoo casino review, is spindoo legit, spindoo daily bonus, spindoo payout, spindoo promo 2026',
 h1='SpinDoo Review 2026: <span class="highlight">Growing New Sweepstakes Platform</span>',
 verdict='SpinDoo is a newer US sweepstakes casino still building out its feature set. The daily SC bonus, welcome offer, and 400+ game catalog give it a functional start. The $100 cash minimum, no VIP or crypto options, and limited promotional depth keep it in Mid Tier for now — but worth monitoring as it develops.',
 schema_body='SpinDoo is a newer US sweepstakes casino with 400+ games, daily SC bonus, and $100 cash minimum redemption.',
 what_is='<p>SpinDoo launched in 2024 as a <strong>US-focused sweepstakes casino</strong> (.us domain) with a clean platform and a growing game library. It\'s in the early-growth phase — functional with a <strong>daily SC bonus</strong> and solid welcome offer, but still building out the depth that High Tier platforms have established over years.</p><p>For multi-platform farmers, SpinDoo represents a low-friction addition: sign up, collect the daily SC, and let it accumulate toward the $100 floor. Don\'t expect heavy promotional events or a VIP program yet — those are earned over time as the platform matures.</p>',
 promo='<p>SpinDoo offers a <strong>welcome offer</strong> for new accounts with SC credited on registration. The daily SC bonus provides ongoing earning. Check the promotions page regularly as the platform adds events and seasonal bonuses over time.</p>',
 steps=['Visit <a href="https://www.spindoo.us/?r=28402933" target="_blank" rel="noopener">spindoo.us</a> and sign up.','Verify your email to receive your welcome offer.','Log in daily to collect the SC bonus.','Play through the 400+ game library.','Reach $100 SC for your first cash redemption.'],
 pros=['US domain and operation — domestically focused','Daily SC login bonus — consistent base earning','Welcome offer for new players','400+ game library covering core titles','Low-friction signup process','Room to grow — early-stage platform'],
 cons=['$100 cash minimum — no lower-tier options','No VIP loyalty program','No gift card or crypto redemptions','400+ games — limited vs. competitors','Short operational history — less established trust','Limited promotional calendar'],
 games_detail='<p>SpinDoo currently offers <strong>400+ games</strong> with a focus on slots. The catalog covers the core volatility ranges and includes basic table game options. As a newer platform, expect regular additions as the library expands. Mobile performance is smooth and the interface is clean.</p>',
 bonus_detail='<p>SpinDoo provides a <strong>welcome SC offer</strong> on signup and a <strong>daily SC bonus</strong> on each login. The promotional calendar is developing — seasonal events and promos are expected to increase as the platform grows. Currently most value comes from the daily login and welcome package.</p>',
 payout_detail='<p>SpinDoo requires <strong>$100 SC</strong> minimum for cash redemption. Complete KYC identity verification in your account settings. Processing takes <strong>3–7 business days</strong>. No gift card or crypto options currently available.</p>',
 faqs=[
  ('Is SpinDoo legit?','SpinDoo is a legitimate newer US sweepstakes casino launched in 2024. Shorter track record but operational and paying out players.'),
  ('What is the minimum payout at SpinDoo?','$100 SC for cash redemption.'),
  ('What is the daily bonus at SpinDoo?','A daily SC bonus on login — check the platform for current amounts.'),
  ('Does SpinDoo support crypto payouts?','No. Cash redemption only at $100 minimum.'),
  ('Is SpinDoo available in Canada?','No. US only.'),
  ('Is SpinDoo a legit .us sweepstakes casino?','Yes — SpinDoo operates as a US-based sweepstakes casino with a .us domain and US player focus.'),
 ]
),

# 5. STACKR
dict(
 slug='stackr', name='Stackr', score='3.7', tier='Mid Tier',
 site_url='https://www.stackrcasino.com', affiliate='https://www.stackrcasino.com/?referralcode=bbde20f1-7e87-497b-862b-c49b3f11024c',
 parent='Stackr Gaming Inc', launch='2023', age='18+',
 daily='Daily SC bonus', welcome='Welcome package on signup',
 min_redeem='$100 SC (cash)', payout_speed='3–7 business days',
 games='500+', r_games='3.7', r_bonus='3.7', r_payout='3.7',
 restricted=['ID','WA','MT','MI','NV','CT'],
 title='Stackr Casino Review 2026 — Legit? Daily SC Bonus, Payouts & Rating',
 meta_desc='Stackr Casino review 2026: 3.7/5. US sweepstakes casino with 500+ games, daily SC, $100 cash minimum. Is Stackr legit? Full honest review for sweepstakes players.',
 keywords='stackr casino review, is stackr legit, stackr daily bonus, stackr payout, stackr casino promo code 2026',
 h1='Stackr Casino Review 2026: <span class="highlight">Stack Daily SC on a Solid Mid Tier Platform</span>',
 verdict='Stackr Casino does what its name promises — gives you a daily SC stack to build on. The 500+ game library, welcome package, and referral code tracking make it a competent Mid Tier addition. The $100 cash minimum and no VIP/crypto options are standard limitations. Reliable for daily rotation.',
 schema_body='Stackr Casino is a sweepstakes casino with 500+ games, daily SC login bonus, referral program, and $100 cash minimum redemption.',
 what_is='<p>Stackr Casino lives up to its name: a <strong>sweepstakes platform designed around daily SC accumulation</strong>. Launched in 2023, it has positioned itself as a reliable Mid Tier daily earner with a referral program for players who want a second earning channel alongside the login bonus.</p><p>The <strong>500+ game library</strong> is respectable for the tier, and the referral code system (via unique GUID codes) makes it easy to track your recruiting activity. For multi-platform farmers, Stackr is another clean daily addition that doesn\'t demand heavy management.</p>',
 promo='<p>Stackr provides a <strong>welcome package</strong> for new accounts and an ongoing <strong>referral code system</strong> that rewards active recruits. The daily SC bonus is the core earning mechanism. Seasonal promotions and periodic events add to the baseline earning throughout the year.</p>',
 steps=['Go to <a href="https://www.stackrcasino.com/?referralcode=bbde20f1-7e87-497b-862b-c49b3f11024c" target="_blank" rel="noopener">stackrcasino.com</a> and register.','Complete email verification to activate your welcome package.','Log in daily for your SC bonus.','Use your personal referral code to earn from recruits.','Reach $100 SC for your first cash redemption.'],
 pros=['Daily SC bonus — consistent farmable earning','500+ game library — solid for Mid Tier','Referral program with unique code tracking','Welcome package for new players','US-focused operation','Good for multi-platform daily rotation'],
 cons=['$100 cash minimum','No VIP loyalty program','No gift card or crypto redemptions','Medium promotional frequency beyond daily SC','Canada not available'],
 games_detail='<p>Stackr Casino offers <strong>500+ games</strong> across slots, table game basics, and specialty titles. The catalog covers all main volatility ranges for slots with smooth mobile performance. Table games include the standard blackjack, roulette, and poker variants. Regular new additions expected as the platform grows.</p>',
 bonus_detail='<p>Stackr\'s daily earning structure is built around the <strong>daily SC login bonus</strong> plus the <strong>referral program</strong>. Players who actively recruit add a meaningful second earning channel. The welcome package front-loads new account value, and seasonal promotions supplement the base earning calendar.</p>',
 payout_detail='<p>Stackr requires <strong>$100 SC</strong> minimum for cash redemption. Complete KYC identity verification before submitting. Processing takes <strong>3–7 business days</strong>. No gift card or crypto options available.</p>',
 faqs=[
  ('Is Stackr Casino legit?','Yes. Stackr Casino is a legitimate US sweepstakes casino operating since 2023 with a consistent payout record.'),
  ('What is the daily bonus at Stackr?','A daily SC login bonus — stack it each day toward your $100 redemption floor.'),
  ('What is the minimum payout at Stackr?','$100 SC for cash redemption.'),
  ('Does Stackr have a referral program?','Yes — use your unique referral code to earn additional SC from players you recruit.'),
  ('Is Stackr available in Canada?','No. US only.'),
  ('Does Stackr support crypto payouts?','No. Cash redemption only.'),
 ]
),

# 6. GOLDRUSHCITY
dict(
 slug='goldrushcity', name='GoldRushCity', score='3.6', tier='Mid Tier',
 site_url='https://www.goldrushcity.com', affiliate='https://www.goldrushcity.com/',
 parent='GoldRushCity Inc', launch='2023', age='18+',
 daily='Daily SC login bonus', welcome='Welcome offer on signup',
 min_redeem='$100 SC (cash)', payout_speed='5–10 business days',
 games='450+', r_games='3.6', r_bonus='3.6', r_payout='3.5',
 restricted=['ID','WA','MT','MI','NV','CT'],
 title='GoldRushCity Casino Review 2026 — Legit? Daily Bonus, Payouts & Rating',
 meta_desc='GoldRushCity review 2026: 3.6/5. Sweepstakes casino with daily SC bonus, 450+ games, $100 cash minimum. Is GoldRushCity legit? Full honest review for US players.',
 keywords='goldrushcity casino review, is goldrushcity legit, goldrushcity daily bonus, goldrushcity payout, goldrushcity review 2026',
 h1='GoldRushCity Review 2026: <span class="highlight">Gold Rush Theme, Daily SC Earning</span>',
 verdict='GoldRushCity is a themed sweepstakes casino with a gold rush aesthetic and a functional daily SC bonus. The 450+ game library and welcome offer make it a viable Mid Tier addition. Processing times (5–10 days) are slower than competitors and the $100 minimum is standard. Worth adding to a rotation for the daily SC alone.',
 schema_body='GoldRushCity is a sweepstakes casino with gold rush theming, 450+ games, daily SC login bonus, and $100 cash minimum redemption.',
 what_is='<p>GoldRushCity brings a <strong>gold rush theme</strong> to the sweepstakes casino space — a visual identity that leans into the treasure-hunting angle of daily SC farming. Beyond the branding, it\'s a functional Mid Tier sweepstakes casino with a <strong>daily SC login bonus</strong> and a <strong>450+ game library</strong> covering the core player experience.</p><p>For multi-platform farmers, GoldRushCity adds another daily earning channel with straightforward mechanics — login, collect SC, play games, redeem. No complex VIP tracking or crypto setup required. Just a clean daily addition.</p>',
 promo='<p>GoldRushCity provides a <strong>welcome offer</strong> for new accounts and a <strong>daily SC login bonus</strong> for ongoing earning. Check the promotions section for current offer details. Seasonal events and themed promotions align with the gold rush aesthetic.</p>',
 steps=['Visit <a href="https://www.goldrushcity.com/" target="_blank" rel="noopener">goldrushcity.com</a> and create an account.','Verify your email to receive your welcome offer.','Log in daily to collect the SC login bonus.','Explore the 450+ themed game library.','Accumulate $100 SC for cash redemption.'],
 pros=['Daily SC login bonus — consistent earning','Gold rush themed experience — fun presentation','Welcome offer for new players','450+ game library with themed slots','US-focused operation','Straightforward platform — easy daily routine'],
 cons=['5–10 day processing — slower than most competitors','$100 minimum — no lower-tier redemption','No VIP program','No gift card or crypto options','Smaller library than High Tier platforms','Canada not available'],
 games_detail='<p>GoldRushCity offers <strong>450+ games</strong> with a thematic emphasis on gold and treasure-themed slots. Coverage extends to standard video slots, basic table games, and specialty titles. The themed aesthetic is consistent across the catalog. Mobile performance is smooth.</p>',
 bonus_detail='<p>GoldRushCity\'s core earning mechanism is the <strong>daily SC login bonus</strong> supplemented by the welcome offer and themed seasonal promotions. The gold rush aesthetic extends into the promotional calendar with relevant seasonal events. Frequency is medium — reliable but not heavy.</p>',
 payout_detail='<p>GoldRushCity requires <strong>$100 SC</strong> minimum for cash redemption. Processing takes <strong>5–10 business days</strong> — slower than the industry norm. Complete KYC identity verification before submitting. No gift card or crypto options available.</p>',
 faqs=[
  ('Is GoldRushCity legit?','Yes. GoldRushCity is a legitimate sweepstakes casino with a consistent payout track record, though processing times are slower than average.'),
  ('What is the daily bonus at GoldRushCity?','A daily SC login bonus — check the platform for current amounts.'),
  ('What is the minimum payout at GoldRushCity?','$100 SC for cash redemption.'),
  ('How long do GoldRushCity payouts take?','5–10 business days — slower than competitors. Plan accordingly.'),
  ('Does GoldRushCity have crypto payouts?','No. Cash redemption only at $100 minimum.'),
  ('Is GoldRushCity available in Canada?','No. US only.'),
 ]
),

# 7. MEGAFRENZY
dict(
 slug='megafrenzy', name='MegaFrenzy', score='3.7', tier='Mid Tier',
 site_url='https://megafrenzy.com', affiliate='https://affiliates.routy.app/route/114341?affId=3353&ts=5005447',
 parent='Skillzz Gaming Group (Malta)', launch='2024', age='18+',
 daily='Daily SC login bonus', welcome='Welcome package on signup',
 min_redeem='$10 SC (gift cards) / $50 SC (cash)', payout_speed='2–5 business days',
 games='600+', r_games='3.7', r_bonus='3.7', r_payout='3.8',
 restricted=['ID','WA','MT','MI','NV'],
 title='MegaFrenzy Casino Review 2026 — Legit? $10 Gift Card Min, Daily SC & Rating',
 meta_desc='MegaFrenzy review 2026: 3.7/5. Skillzz Gaming Group. $10 gift card minimum, daily SC login, 600+ games. Is MegaFrenzy legit? Full honest review for US sweepstakes players.',
 keywords='megafrenzy casino review, is megafrenzy legit, megafrenzy daily bonus, megafrenzy payout, megafrenzy promo 2026',
 h1='MegaFrenzy Review 2026: <span class="highlight">$10 Gift Card Floor on Skillzz Infrastructure</span>',
 verdict='MegaFrenzy runs on Skillzz Gaming Group infrastructure — the same Malta-licensed backend behind Rolla and several routy-network platforms. The $10 gift card minimum makes first redemptions highly accessible, and the 600+ game library is solid for a Mid Tier platform. A reliable addition to any daily rotation.',
 schema_body='MegaFrenzy is a Skillzz Gaming Group sweepstakes casino with $10 gift card minimum, daily SC login bonus, 600+ games, and 2–5 day processing.',
 what_is='<p>MegaFrenzy is operated by <strong>Skillzz Gaming Group</strong> (Malta) — placing it in the same reliable operator network as Rolla and other routy-affiliate casinos. Launched in 2024, it launched with the full Skillzz infrastructure in place, meaning proven payments, game catalog, and compliance from day one.</p><p>The platform\'s most notable feature is the <strong>$10 gift card minimum</strong> — among the lowest redemption floors available. For new players or those building up SC from scratch, MegaFrenzy offers a meaningful early cash-out option before reaching the $50–$100 floors of most competitors.</p>',
 promo='<p>MegaFrenzy provides a <strong>welcome package</strong> for new accounts. The daily SC login bonus provides ongoing earning. As a Skillzz platform, it benefits from the operator\'s established promotional calendar with seasonal events and periodic reload bonuses.</p>',
 steps=['Visit <a href="https://affiliates.routy.app/route/114341?affId=3353&ts=5005447" target="_blank" rel="noopener">MegaFrenzy Casino</a> and register.','Verify your email to activate your welcome package.','Log in daily for the SC login bonus.','Explore the 600+ game library.','Cash out as low as $10 SC with a gift card redemption.'],
 pros=['$10 gift card minimum — most accessible redemption in Mid Tier','$50 cash minimum — below the $100 standard','Skillzz Gaming Group — proven Malta-licensed infrastructure','Daily SC login bonus','600+ game library','2–5 day processing — faster than many Mid Tier competitors'],
 cons=['Malta-licensed (not US-regulated)','No VIP loyalty program','No cryptocurrency redemption','Medium promotional frequency','Canada not available'],
 games_detail='<p>MegaFrenzy offers <strong>600+ games</strong> from the Skillzz catalog — a solid library for a Mid Tier platform. Slots across all volatility levels form the core, with table game coverage (blackjack, roulette, baccarat) and specialty titles rounding out the selection. Mobile optimized and regularly updated.</p>',
 bonus_detail='<p>MegaFrenzy\'s daily SC login bonus provides consistent baseline earning. The Skillzz promotional calendar adds seasonal events and reload bonuses throughout the year. The key differentiator is the <strong>$10 gift card floor</strong> — you can convert daily SC into gift card value after just 10 qualifying logins at most rates.</p>',
 payout_detail='<p>MegaFrenzy offers <strong>$10 SC for gift cards</strong> and <strong>$50 SC for cash</strong> as redemption minimums. Complete KYC verification before submitting. Processing takes <strong>2–5 business days</strong> — faster than the 5–10 days common at some Mid Tier competitors.</p>',
 faqs=[
  ('Is MegaFrenzy legit?','Yes. MegaFrenzy is operated by Skillzz Gaming Group (Malta) — a proven sweepstakes operator since 2021.'),
  ('What is the minimum payout at MegaFrenzy?','$10 SC for gift cards and $50 SC for cash redemptions.'),
  ('What is the daily bonus at MegaFrenzy?','A daily SC login bonus — check the platform for current amounts.'),
  ('Who operates MegaFrenzy?','Skillzz Gaming Group, a Malta-based gaming operator.'),
  ('Does MegaFrenzy support crypto payouts?','No. Gift card and cash redemptions only.'),
  ('Is MegaFrenzy available in Canada?','No. US only.'),
 ]
),

# 8. JACKPOTRABBIT
dict(
 slug='jackpotrabbit', name='JackpotRabbit', score='3.7', tier='Mid Tier',
 site_url='https://jackpotrabbit.com', affiliate='https://jackpotrabbit.com/?invited_by=8ZGOFC',
 parent='JackpotRabbit Ltd', launch='2023', age='18+',
 daily='Daily SC login bonus', welcome='Invite-based welcome offer',
 min_redeem='$100 SC (cash)', payout_speed='3–7 business days',
 games='500+', r_games='3.7', r_bonus='3.7', r_payout='3.6',
 restricted=['ID','WA','MT','MI','NV','CT'],
 title='JackpotRabbit Casino Review 2026 — Legit? Daily Bonus, Payouts & Rating',
 meta_desc='JackpotRabbit review 2026: 3.7/5. Invite-based sweepstakes casino, 500+ games, daily SC login bonus, $100 cash minimum. Is JackpotRabbit legit? Full honest review.',
 keywords='jackpotrabbit casino review, is jackpotrabbit legit, jackpotrabbit daily bonus, jackpotrabbit payout, jackpotrabbit promo 2026',
 h1='JackpotRabbit Review 2026: <span class="highlight">Invite-Based Daily SC Platform</span>',
 verdict='JackpotRabbit runs on an invite-based model — you sign up via someone\'s referral code, and they get rewarded for your activity. The platform itself is solid: 500+ games, consistent daily SC login bonus, and a functional $100 cash redemption pathway. Good Mid Tier daily addition for multi-platform rotation.',
 schema_body='JackpotRabbit is an invite-based sweepstakes casino with 500+ games, daily SC login bonus, and $100 cash minimum redemption.',
 what_is='<p>JackpotRabbit uses an <strong>invite-based registration model</strong> — new players sign up via a referral link, and both the referrer and new player benefit from the arrangement. This model encourages community growth while keeping the platform\'s user acquisition cost low.</p><p>For players, the experience is standard sweepstakes: <strong>500+ games</strong>, a <strong>daily SC login bonus</strong>, and a $100 cash redemption floor. JackpotRabbit is a clean, functional Mid Tier platform that rewards consistent daily play without complex bonus structures.</p>',
 promo='<p>JackpotRabbit provides an <strong>invite-based welcome offer</strong> for new players who sign up via a referral link. The daily SC login bonus is the main ongoing earning mechanism. Seasonal promotions and periodic events supplement the baseline earning throughout the year.</p>',
 steps=['Visit <a href="https://jackpotrabbit.com/?invited_by=8ZGOFC" target="_blank" rel="noopener">JackpotRabbit</a> and create your account.','Complete email verification to receive your welcome offer.','Log in daily for your SC login bonus.','Explore the 500+ game catalog.','Accumulate $100 SC for your first cash redemption.'],
 pros=['Invite-based model — community-driven growth','Daily SC login bonus — consistent earning','500+ game library','Welcome offer for invited new players','US-focused sweepstakes platform','Clean, straightforward experience'],
 cons=['$100 cash minimum — standard but not low','No VIP loyalty program','No gift card or crypto redemptions','Requires invite to unlock best welcome offer','Canada not available','Medium promotional frequency'],
 games_detail='<p>JackpotRabbit offers <strong>500+ games</strong> covering slots (all volatility ranges), basic table games, and specialty titles. The catalog delivers a solid core sweepstakes experience with smooth mobile performance and regular new additions. Slot selection is the highlight.</p>',
 bonus_detail='<p>JackpotRabbit\'s invite system means new players start with a better welcome offer than walk-in signups. The <strong>daily SC login bonus</strong> is the ongoing earning core. Referral rewards activate when your recruits are active, adding a secondary earning stream for engaged community members.</p>',
 payout_detail='<p>JackpotRabbit requires <strong>$100 SC</strong> minimum for cash redemption. Complete KYC identity verification in your account settings before submitting. Processing takes <strong>3–7 business days</strong>. No gift card or crypto options.</p>',
 faqs=[
  ('Is JackpotRabbit legit?','Yes. JackpotRabbit is a legitimate sweepstakes casino operating since 2023 with a verifiable invite program and consistent payouts.'),
  ('Do I need an invite to join JackpotRabbit?','You can sign up without an invite, but signing up via a referral link unlocks a better welcome offer.'),
  ('What is the minimum payout at JackpotRabbit?','$100 SC for cash redemption.'),
  ('What is the daily bonus at JackpotRabbit?','A daily SC login bonus — check the platform for current amounts.'),
  ('Does JackpotRabbit have crypto payouts?','No. Cash redemption only at $100 minimum.'),
  ('Is JackpotRabbit available in Canada?','No. US only.'),
 ]
),

# 9. SCARLETSANDS
dict(
 slug='scarletsands', name='ScarletSands', score='3.8', tier='Mid Tier',
 site_url='https://scarletsands.com', affiliate='https://affiliates.routy.app/route/114302?affId=3353&ts=5005447',
 parent='Skillzz Gaming Group (Malta)', launch='2024', age='18+',
 daily='Daily SC login bonus', welcome='Welcome offer on signup',
 min_redeem='$10 SC (gift cards) / $50 SC (cash)', payout_speed='2–5 business days',
 games='600+', r_games='3.8', r_bonus='3.8', r_payout='3.8',
 restricted=['ID','WA','MT','MI','NV'],
 title='ScarletSands Casino Review 2026 — Legit? $10 Gift Card, Daily SC & Rating',
 meta_desc='ScarletSands review 2026: 3.8/5. Skillzz Gaming Group, $10 gift card minimum, daily SC bonus, 600+ games. Is ScarletSands legit? Full honest review for US players.',
 keywords='scarletsands casino review, is scarletsands legit, scarletsands daily bonus, scarletsands payout, scarletsands review 2026',
 h1='ScarletSands Review 2026: <span class="highlight">Skillzz Platform with Low Gift Card Floor</span>',
 verdict='ScarletSands operates on Skillzz Gaming Group infrastructure — Malta-licensed, routy-network backed, and proven. The $10 gift card minimum and $50 cash floor make it one of the more accessible Skillzz platforms for new sweepstakes players. 600+ games and 2–5 day processing round out a solid Mid Tier offering.',
 schema_body='ScarletSands is a Skillzz Gaming Group sweepstakes casino with $10 gift card minimum, $50 cash minimum, 600+ games, and 2–5 day processing.',
 what_is='<p>ScarletSands is operated by <strong>Skillzz Gaming Group</strong> (Malta), placing it in the same proven operator network as Rolla, MegaFrenzy, and several other routy-affiliate casinos. Launched in 2024, it came online with full Skillzz infrastructure — established payments, game catalog, and compliance systems.</p><p>The platform targets players who want the <strong>Skillzz reliability</strong> with a fresh visual brand. The $10 gift card minimum and $50 cash floor make it one of the most accessible entry points in the Mid Tier. Combined with the daily SC login bonus and solid 600+ game library, ScarletSands is a clean daily rotation pick.</p>',
 promo='<p>ScarletSands provides a <strong>welcome offer</strong> for new accounts and a <strong>daily SC login bonus</strong> for ongoing earning. The Skillzz promotional calendar adds seasonal events and reload bonuses throughout the year.</p>',
 steps=['Visit <a href="https://affiliates.routy.app/route/114302?affId=3353&ts=5005447" target="_blank" rel="noopener">ScarletSands Casino</a> and register.','Complete email verification to claim your welcome offer.','Log in daily for the SC login bonus.','Explore the 600+ game library.','Redeem as low as $10 SC for gift cards.'],
 pros=['$10 gift card minimum — highly accessible first redemption','$50 cash minimum — below the $100 standard','Skillzz Gaming Group infrastructure — Malta-licensed and proven','Daily SC login bonus — consistent earning','600+ game library','2–5 day processing — above average speed'],
 cons=['Malta-licensed (not US-regulated)','No VIP loyalty program','No cryptocurrency redemption','Medium promotional frequency','Canada not available'],
 games_detail='<p>ScarletSands offers <strong>600+ games</strong> from the Skillzz catalog. Slots form the core with full volatility range coverage, supplemented by table games (blackjack, roulette, baccarat) and specialty titles. Mobile-optimized and regularly updated with new Skillzz software partner releases.</p>',
 bonus_detail='<p>ScarletSands provides a <strong>daily SC login bonus</strong> supplemented by the welcome package and Skillzz seasonal promotional calendar. The standout accessibility feature is the <strong>$10 gift card floor</strong> — reach first redemption far sooner than $100-minimum competitors.</p>',
 payout_detail='<p>ScarletSands offers <strong>$10 SC for gift cards</strong> and <strong>$50 SC for cash</strong>. Complete KYC before submitting. Processing takes <strong>2–5 business days</strong> — above the Mid Tier average. No crypto options.</p>',
 faqs=[
  ('Is ScarletSands legit?','Yes. ScarletSands runs on Skillzz Gaming Group infrastructure — a proven Malta-licensed sweepstakes operator.'),
  ('What is the minimum payout at ScarletSands?','$10 SC for gift cards and $50 SC for cash redemptions.'),
  ('Who operates ScarletSands?','Skillzz Gaming Group, a Malta-based gaming operator.'),
  ('What is the daily bonus at ScarletSands?','A daily SC login bonus — check the platform for current amounts.'),
  ('Does ScarletSands support crypto payouts?','No. Gift card and cash redemptions only.'),
  ('Is ScarletSands available in Canada?','No. US only.'),
 ]
),

# 10. LUCKYBITSVGAS
dict(
 slug='luckybitsveg', name='LuckyBitsVegas', score='3.7', tier='Mid Tier',
 site_url='https://luckybitsveg.com', affiliate='https://affiliates.routy.app/route/114338?affId=3353&ts=5005447',
 parent='Skillzz Gaming Group (Malta)', launch='2024', age='18+',
 daily='Daily SC login bonus', welcome='Welcome offer on signup',
 min_redeem='$10 SC (gift cards) / $50 SC (cash)', payout_speed='2–5 business days',
 games='600+', r_games='3.7', r_bonus='3.7', r_payout='3.8',
 restricted=['ID','WA','MT','MI','NV'],
 title='LuckyBitsVegas Casino Review 2026 — Legit? Daily SC, $10 Gift Card Min & Rating',
 meta_desc='LuckyBitsVegas review 2026: 3.7/5. Skillzz Gaming Group. $10 gift card minimum, daily SC, 600+ games. Is LuckyBitsVegas legit? Full honest review 2026.',
 keywords='luckybitsveg casino review, is luckybitsveg legit, luckybitsveg daily bonus, luckybitsveg payout, luckybitsveg promo 2026',
 h1='LuckyBitsVegas Review 2026: <span class="highlight">Vegas-Themed Skillzz Platform</span>',
 verdict='LuckyBitsVegas brings Vegas branding to the Skillzz Gaming Group infrastructure — the same Malta-licensed backend behind Rolla, MegaFrenzy, and ScarletSands. The $10 gift card minimum, $50 cash floor, and daily SC login bonus make it a straightforward Mid Tier addition. Reliable Skillzz infrastructure with fresh Vegas aesthetic.',
 schema_body='LuckyBitsVegas is a Skillzz Gaming Group sweepstakes casino with Vegas theming, $10 gift card minimum, daily SC login bonus, and 600+ games.',
 what_is='<p>LuckyBitsVegas applies a <strong>Las Vegas aesthetic</strong> to the Skillzz Gaming Group platform — the proven Malta-licensed infrastructure behind several successful routy-network casinos. For players familiar with Rolla or ScarletSands, LuckyBitsVegas will feel immediately familiar in mechanics while offering a fresh visual experience.</p><p>The platform launched in 2024 with full Skillzz infrastructure from day one: established payment rails, proven compliance, and a <strong>600+ game catalog</strong>. The <strong>$10 gift card minimum</strong> and <strong>$50 cash floor</strong> are consistent with other Skillzz platforms and represent some of the most accessible redemption thresholds in the Mid Tier.</p>',
 promo='<p>LuckyBitsVegas offers a <strong>welcome package</strong> for new accounts and a <strong>daily SC login bonus</strong> for ongoing earning. Seasonal promotions draw on the Vegas theme with holiday events and special game features throughout the year.</p>',
 steps=['Visit <a href="https://affiliates.routy.app/route/114338?affId=3353&ts=5005447" target="_blank" rel="noopener">LuckyBitsVegas</a> and create your account.','Verify your email to claim your welcome package.','Log in daily for the SC login bonus.','Explore the Vegas-themed 600+ game library.','Redeem as low as $10 SC for gift cards.'],
 pros=['$10 gift card minimum — highly accessible','$50 cash minimum — below the $100 standard','Skillzz Gaming Group — proven infrastructure','Vegas-themed aesthetic — distinct visual experience','Daily SC login bonus','600+ game library with Vegas-style slots'],
 cons=['Malta-licensed (not US-regulated)','No VIP loyalty program','No cryptocurrency redemption','Medium promotional frequency','Canada not available'],
 games_detail='<p>LuckyBitsVegas offers <strong>600+ games</strong> with a Vegas-forward presentation — slots themed around Vegas icons, card rooms, and classic casino imagery. The Skillzz catalog covers all volatility levels, with table games (blackjack, roulette, baccarat) and specialty titles completing the experience. Mobile performance is strong.</p>',
 bonus_detail='<p>LuckyBitsVegas provides the standard Skillzz earning structure: <strong>daily SC login bonus</strong>, welcome package, and seasonal promotional calendar. The Vegas theme extends into promotional events with holiday and themed bonuses. The $10 gift card floor is the core accessibility differentiator.</p>',
 payout_detail='<p>LuckyBitsVegas offers <strong>$10 SC for gift cards</strong> and <strong>$50 SC for cash</strong>. Complete KYC before withdrawing. Processing takes <strong>2–5 business days</strong>. No crypto options.</p>',
 faqs=[
  ('Is LuckyBitsVegas legit?','Yes. LuckyBitsVegas operates on Skillzz Gaming Group infrastructure — a proven Malta-licensed operator.'),
  ('What is the minimum payout at LuckyBitsVegas?','$10 SC for gift cards and $50 SC for cash redemptions.'),
  ('Who operates LuckyBitsVegas?','Skillzz Gaming Group, a Malta-based sweepstakes gaming operator.'),
  ('What is the daily bonus at LuckyBitsVegas?','A daily SC login bonus — check the platform for current amounts.'),
  ('Does LuckyBitsVegas support crypto payouts?','No. Gift card and cash redemptions only.'),
  ('Is LuckyBitsVegas available in Canada?','No. US only.'),
 ]
),

# 11. CAZINO
dict(
 slug='cazino', name='Cazino', score='3.7', tier='Mid Tier',
 site_url='https://cazino.com', affiliate='https://affiliates.routy.app/route/114303?affId=3353&ts=5005447',
 parent='Skillzz Gaming Group (Malta)', launch='2023', age='18+',
 daily='Daily SC login bonus', welcome='Welcome package on signup',
 min_redeem='$10 SC (gift cards) / $50 SC (cash)', payout_speed='2–5 business days',
 games='700+', r_games='3.8', r_bonus='3.7', r_payout='3.8',
 restricted=['ID','WA','MT','MI','NV'],
 title='Cazino Casino Review 2026 — Legit? $10 Gift Card Min, Daily SC & Rating',
 meta_desc='Cazino review 2026: 3.7/5. Skillzz Gaming Group, $10 gift card floor, 700+ games, daily SC bonus. Is Cazino legit? Full honest review for US sweepstakes players.',
 keywords='cazino casino review, is cazino legit, cazino daily bonus, cazino payout, cazino promo code 2026',
 h1='Cazino Review 2026: <span class="highlight">700+ Games on Skillzz Infrastructure</span>',
 verdict='Cazino is among the larger Skillzz Gaming Group platforms by game count, offering 700+ titles. The $10 gift card minimum, $50 cash floor, and daily SC login bonus make it a consistently attractive Mid Tier pick. Malta-licensed via Skillzz, reliable payments, and above-average game variety.',
 schema_body='Cazino is a Skillzz Gaming Group sweepstakes casino with 700+ games, $10 gift card minimum, daily SC login bonus, and 2–5 day processing.',
 what_is='<p>Cazino is a <strong>Skillzz Gaming Group</strong> platform (Malta) with one of the larger game catalogs in the routy-network: <strong>700+ titles</strong>. This gives it a game variety edge over some of its Skillzz siblings while maintaining the same proven infrastructure, payment rails, and compliance standards.</p><p>The <strong>$10 gift card minimum</strong> and <strong>$50 cash floor</strong> are Skillzz-standard — consistently among the most accessible in the Mid Tier. For multi-platform farmers who want a bigger game catalog from a reliable operator, Cazino fills that gap.</p>',
 promo='<p>Cazino provides a <strong>welcome package</strong> for new accounts. The daily SC login bonus is the ongoing earning mechanism. Skillzz seasonal promotional calendar delivers regular events and reload bonuses throughout the year.</p>',
 steps=['Visit <a href="https://affiliates.routy.app/route/114303?affId=3353&ts=5005447" target="_blank" rel="noopener">Cazino</a> and register.','Complete email verification to receive your welcome offer.','Log in daily for the SC login bonus.','Explore the 700+ game library.','Redeem as low as $10 SC for gift cards.'],
 pros=['700+ games — larger catalog than most Mid Tier peers','$10 gift card minimum — very accessible first redemption','$50 cash minimum — below the $100 standard','Skillzz Gaming Group — Malta-licensed and proven','Daily SC login bonus','2–5 day processing'],
 cons=['Malta-licensed (not US-regulated)','No VIP loyalty program','No cryptocurrency redemption','Medium promotional frequency','Canada not available'],
 games_detail='<p>Cazino offers <strong>700+ games</strong> — one of the larger Skillzz-network catalogs. Coverage spans slots across all variance levels, table games (blackjack, roulette, baccarat, and poker variants), and specialty titles. The broader library provides more variety for players who get bored of smaller catalogs. Mobile performance is smooth.</p>',
 bonus_detail='<p>Cazino\'s daily SC login bonus is supplemented by the Skillzz promotional calendar — seasonal events, reload bonuses, and holiday promotions that run throughout the year. The $10 gift card floor means you can realize value quickly from daily SC accumulation without waiting for $100 minimums.</p>',
 payout_detail='<p>Cazino offers <strong>$10 SC for gift cards</strong> and <strong>$50 SC for cash</strong>. Complete KYC identity verification before submitting. Processing takes <strong>2–5 business days</strong>. No crypto redemption options.</p>',
 faqs=[
  ('Is Cazino legit?','Yes. Cazino operates on Skillzz Gaming Group infrastructure — a proven Malta-licensed sweepstakes operator.'),
  ('What is the minimum payout at Cazino?','$10 SC for gift cards and $50 SC for cash redemptions.'),
  ('Who operates Cazino?','Skillzz Gaming Group (Malta).'),
  ('What is the daily bonus at Cazino?','A daily SC login bonus — check the platform for current amounts.'),
  ('How many games does Cazino have?','700+ games — one of the larger catalogs among Skillzz-network sweepstakes casinos.'),
  ('Is Cazino available in Canada?','No. US only.'),
 ]
),

# 12. SWEEPSHARK
dict(
 slug='sweepshark', name='Sweepshark', score='3.7', tier='Mid Tier',
 site_url='https://sweepshark.com', affiliate='https://affiliates.routy.app/route/114301?affId=3353&ts=5005447',
 parent='Skillzz Gaming Group (Malta)', launch='2024', age='18+',
 daily='Daily SC login bonus', welcome='Welcome package on signup',
 min_redeem='$10 SC (gift cards) / $50 SC (cash)', payout_speed='2–5 business days',
 games='600+', r_games='3.7', r_bonus='3.7', r_payout='3.8',
 restricted=['ID','WA','MT','MI','NV'],
 title='Sweepshark Casino Review 2026 — Legit? $10 Gift Card Min, Daily SC & Rating',
 meta_desc='Sweepshark review 2026: 3.7/5. Skillzz Gaming Group. $10 gift card min, daily SC bonus, 600+ games. Is Sweepshark legit? Full honest review for US sweepstakes players.',
 keywords='sweepshark casino review, is sweepshark legit, sweepshark daily bonus, sweepshark payout, sweepshark promo 2026',
 h1='Sweepshark Review 2026: <span class="highlight">Skillzz Platform with Shark Branding</span>',
 verdict='Sweepshark is another solid Skillzz Gaming Group platform — same proven Malta-licensed infrastructure, $10 gift card minimum, $50 cash floor, and daily SC login bonus. Fresh branding on proven rails. Good Mid Tier addition for players building up a wide sweepstakes portfolio.',
 schema_body='Sweepshark is a Skillzz Gaming Group sweepstakes casino with $10 gift card minimum, daily SC login bonus, 600+ games, and 2–5 day processing.',
 what_is='<p>Sweepshark applies shark-themed branding to the <strong>Skillzz Gaming Group platform</strong> (Malta) — joining Rolla, Cazino, ScarletSands, MegaFrenzy, and LuckyBitsVegas in the routy-network Skillzz family. For players already running other Skillzz platforms, Sweepshark adds another <strong>independent promotional calendar</strong> and earning channel from the same proven infrastructure.</p><p>The <strong>$10 gift card minimum</strong> and <strong>$50 cash floor</strong> are consistent across the Skillzz network. Combined with the daily SC login bonus and 600+ game library, Sweepshark is a clean addition to any wide-portfolio sweepstakes strategy.</p>',
 promo='<p>Sweepshark provides a <strong>welcome package</strong> for new accounts. The daily SC login bonus is the core earning mechanism. Skillzz promotional calendar adds seasonal events and reload bonuses throughout the year, running independently of the other Skillzz platforms.</p>',
 steps=['Visit <a href="https://affiliates.routy.app/route/114301?affId=3353&ts=5005447" target="_blank" rel="noopener">Sweepshark Casino</a> and register.','Verify email to receive your welcome package.','Log in daily for the SC login bonus.','Explore the 600+ game library.','Redeem as low as $10 SC for gift cards.'],
 pros=['$10 gift card minimum — accessible first redemption','$50 cash minimum — below the $100 standard','Skillzz Gaming Group — Malta-licensed infrastructure','Independent promo calendar from other Skillzz platforms','Daily SC login bonus','600+ game library'],
 cons=['Malta-licensed (not US-regulated)','No VIP loyalty program','No cryptocurrency redemption','Medium promotional frequency','Canada not available','Multiple Skillzz accounts require some management overhead'],
 games_detail='<p>Sweepshark offers <strong>600+ games</strong> from the Skillzz catalog — slots across all volatility levels, table game basics (blackjack, roulette, baccarat), and specialty titles. The shark theme extends into the game presentation. Mobile-optimized with regular Skillzz catalog updates.</p>',
 bonus_detail='<p>Sweepshark runs its own Skillzz promotional calendar — seasonal events and reload bonuses that operate independently of other Skillzz platforms. This means stacking Sweepshark with Rolla, Cazino, and ScarletSands gives multiple simultaneous earning channels from one proven operator, not duplicating the same promotions.</p>',
 payout_detail='<p>Sweepshark offers <strong>$10 SC for gift cards</strong> and <strong>$50 SC for cash</strong>. Complete KYC before withdrawing. Processing takes <strong>2–5 business days</strong>. No crypto redemption options.</p>',
 faqs=[
  ('Is Sweepshark legit?','Yes. Sweepshark operates on Skillzz Gaming Group infrastructure — a proven Malta-licensed sweepstakes operator.'),
  ('What is the minimum payout at Sweepshark?','$10 SC for gift cards and $50 SC for cash redemptions.'),
  ('Who operates Sweepshark?','Skillzz Gaming Group (Malta).'),
  ('What is the daily bonus at Sweepshark?','A daily SC login bonus — check the platform for current amounts.'),
  ('Is Sweepshark related to other Skillzz casinos?','Yes — Sweepshark shares infrastructure with Rolla, Cazino, ScarletSands, MegaFrenzy, and LuckyBitsVegas, but each runs its own independent promotional calendar.'),
  ('Is Sweepshark available in Canada?','No. US only.'),
 ]
),

] # end CASINOS

if __name__ == '__main__':
    built = 0
    for c in CASINOS:
        html = build(c)
        path = os.path.join(BASE, f"review-{c['slug']}.html")
        with open(path, 'w', encoding='utf-8') as f:
            f.write(html)
        print(f"  OK  review-{c['slug']}.html")
        built += 1
    print(f"\nDone — {built} review pages written.")
