#!/usr/bin/env python3
"""Part 4 — 12 new casino review pages.
Casinos: SpeedSweeps, DimeSweeps, RichSweeps, SweepsRoyal, SpinBlitz, American Luck,
         FortuneWheelz, FunzCity, Legendz, Sidepot, SpinQuest, LunaLand Casino
"""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from seo_all_reviews import build, BASE

CASINOS = [

# 1. SPEEDSWEEPS
dict(
 slug='speedsweeps', name='SpeedSweeps', score='4.3', tier='High Tier',
 site_url='https://www.speedsweeps.com', affiliate='https://speedsweeps.com/?ref=r_poponline63',
 parent='SpeedSweeps (Delaware)', launch='2022', age='18+',
 daily='Random daily bonus', welcome='Welcome package on signup',
 min_redeem='$100 SC (cash) / $100 SC (crypto)', payout_speed='3–5 business days',
 games='1,200+', r_games='4.3', r_bonus='4.2', r_payout='4.3',
 restricted=['ID','WA','MT','MI','NV','KY'],
 title='SpeedSweeps Casino Review 2026 — Legit? Bonuses, Payouts & Rating',
 meta_desc='SpeedSweeps review 2026: 4.3/5. Delaware-regulated flagship. 1,200+ games, cash & crypto redemptions, HIGH promo calendar. Is SpeedSweeps legit? Full honest review.',
 keywords='speedsweeps review, is speedsweeps legit, speedsweeps daily bonus, speedsweeps payout, speedsweeps promo 2026',
 h1='SpeedSweeps Review 2026: <span class="highlight">Delaware Flagship with Crypto Payouts</span>',
 verdict='SpeedSweeps is the flagship of a well-built Delaware-regulated family. High promotional frequency, 1,200+ games, and dual cash + crypto payouts at $100 each make it a strong High Tier pick. The random daily bonus is the main limitation — earnings aren\'t predictable — but the promo calendar more than compensates.',
 schema_body='SpeedSweeps is a Delaware-regulated sweepstakes casino with 1,200+ games, cash and crypto redemptions at $100 minimum, and high promotional frequency.',
 what_is='<p>SpeedSweeps is the <strong>flagship platform</strong> of a Delaware-regulated family that also includes DimeSweeps, RichSweeps, and SweepsRoyal. Launched in 2022, it has the most established track record of the group and serves as the benchmark for its sister sites.</p><p>The platform stands out for its <strong>HIGH promotional frequency</strong> — regular bonuses, seasonal events, and a welcome offer that front-loads value for new accounts. With <strong>1,200+ games</strong> and both cash and crypto redemption pathways, SpeedSweeps covers all the bases for serious sweepstakes players.</p><p>The one caveat: the daily bonus is <strong>random, not fixed</strong>. You won\'t get the same SC every login. For predictable daily farming, God Tier platforms like Stake.us or McLuck are better. SpeedSweeps rewards you through promos, not daily consistency.</p>',
 promo='<p>SpeedSweeps offers a <strong>welcome package</strong> for new accounts. The exact amount varies — check the site directly for current offers. Ongoing promotions include seasonal events, reload bonuses, and social media giveaways that keep active players well-supplied.</p>',
 steps=['Visit <a href="https://speedsweeps.com/?ref=r_poponline63" target="_blank" rel="noopener">speedsweeps.com</a> and click Sign Up.','Complete registration with email and personal details.','Verify your email to activate your account.','Claim your welcome offer and explore the promo page.','Use the promo calendar for the best SC value.'],
 pros=['Delaware-regulated — established legal foundation','1,200+ game library across all major categories','Dual redemption: cash AND crypto at $100 each','HIGH promotional frequency with regular bonuses','VIP program with progression rewards','Sister sites (DimeSweeps, RichSweeps, SweepsRoyal) extend value'],
 cons=['Random daily bonus — not predictable for farming','Only slots count toward playthrough requirements','No gift card redemption option','$100 minimum on both cash and crypto payouts','Canada not available'],
 games_detail='<p>SpeedSweeps carries <strong>1,200+ games</strong> across slots, table games, and specialty titles. The catalog spans all volatility levels — low, medium, and high — from multiple software providers. The slot library is the clear highlight, with regular new additions. Table game selection includes blackjack, roulette, and poker variants.</p>',
 bonus_detail='<p>Daily bonuses at SpeedSweeps are <strong>random in amount</strong> — not a fixed daily credit. The real value lives in the <strong>HIGH promo calendar</strong>: seasonal events, holiday bonuses, reload offers, and social media giveaways. New players should pay attention to the welcome package, which front-loads the most value.</p>',
 payout_detail='<p>SpeedSweeps requires <strong>$100 SC</strong> minimum for both cash and crypto redemptions. Complete identity verification (KYC) in your account settings before submitting. Processing takes <strong>3–5 business days</strong> for cash; crypto processing is generally faster.</p>',
 faqs=[
  ('Is SpeedSweeps legit?','Yes. SpeedSweeps is a Delaware-regulated sweepstakes casino that has been operating since 2022 with a solid payout record.'),
  ('What is the daily bonus at SpeedSweeps?','SpeedSweeps uses a random daily bonus structure — the amount varies each day rather than being a fixed SC credit.'),
  ('Does SpeedSweeps offer crypto payouts?','Yes. SpeedSweeps supports both cash and cryptocurrency redemptions, both with a $100 SC minimum.'),
  ('What is the minimum cash out at SpeedSweeps?','$100 SC for both cash and crypto redemptions.'),
  ('Does SpeedSweeps have sister sites?','Yes — DimeSweeps, RichSweeps, and SweepsRoyal all run on the same infrastructure and are part of the same Delaware-based family.'),
  ('Is SpeedSweeps available in Canada?','No. SpeedSweeps is US only.'),
 ]
),

# 2. DIMESWEEPS
dict(
 slug='dimesweeps', name='DimeSweeps', score='4.2', tier='High Tier',
 site_url='https://www.dimesweeps.com', affiliate='https://dimesweeps.com/?ref=r_poponline63',
 parent='SpeedSweeps family (Delaware)', launch='2023', age='18+',
 daily='Random daily bonus', welcome='Welcome offer on signup',
 min_redeem='$100 SC (cash) / $100 SC (crypto)', payout_speed='3–5 business days',
 games='1,100+', r_games='4.2', r_bonus='4.1', r_payout='4.3',
 restricted=['ID','WA','MT','MI','NV','KY'],
 title='DimeSweeps Casino Review 2026 — Legit? Bonuses, Payouts & Rating',
 meta_desc='DimeSweeps review 2026: 4.2/5. Part of the SpeedSweeps family. Delaware-regulated, 1,100+ games, cash & crypto payouts, HIGH promos. Is DimeSweeps legit? Full review.',
 keywords='dimesweeps review, is dimesweeps legit, dimesweeps daily bonus, dimesweeps payout, dimesweeps promo 2026',
 h1='DimeSweeps Review 2026: <span class="highlight">High-Value SpeedSweeps Sister Site</span>',
 verdict='DimeSweeps earns its Editors\' Choice status as a strong High Tier performer. Part of the proven SpeedSweeps family, it combines 1,100+ games, dual cash and crypto payouts, and a genuinely high promo frequency. The random daily bonus is less ideal for farming, but the promotional calendar delivers consistent value.',
 schema_body='DimeSweeps is a Delaware-regulated sweepstakes casino from the SpeedSweeps family, offering 1,100+ games, cash and crypto redemptions at $100 minimum, and high promotional frequency.',
 what_is='<p>DimeSweeps is a <strong>sister site to SpeedSweeps</strong>, operating under the same Delaware-regulated infrastructure. It shares the game library, payment systems, and VIP structure of the parent platform while running its own promotional calendar and branding.</p><p>For players who want to maximize SC earnings across related platforms, running DimeSweeps alongside SpeedSweeps means access to <strong>two independent promo calendars</strong> from the same proven infrastructure. The <strong>1,100+ game library</strong> covers slots, table games, and specialty titles — enough to keep any rotation fresh.</p>',
 promo='<p>DimeSweeps provides a <strong>welcome offer</strong> for new accounts. Check the site for the current package. Like all SpeedSweeps family sites, the ongoing promo calendar is where the best SC value lives — seasonal events, reload bonuses, and regular giveaways.</p>',
 steps=['Visit <a href="https://dimesweeps.com/?ref=r_poponline63" target="_blank" rel="noopener">dimesweeps.com</a> and register.','Complete email verification to activate your account.','Claim your welcome offer from the promotions page.','Add DimeSweeps to your daily rotation alongside other SpeedSweeps sites.','Monitor the promo calendar for the highest-value events.'],
 pros=['SpeedSweeps family infrastructure — proven and reliable','1,100+ game library with strong slot selection','Cash AND crypto redemptions at $100 each','HIGH promotional frequency and calendar','VIP program with loyalty rewards','Delaware-regulated operation'],
 cons=['Random daily bonus — unpredictable for consistent farming','Only slot play counts toward playthrough','$100 minimum on all redemptions','No gift card option','Canada not available'],
 games_detail='<p>DimeSweeps shares much of the SpeedSweeps game catalog — <strong>1,100+ titles</strong> spanning slots, table games, and specialty games. Slots dominate with providers across all volatility ranges. New titles added regularly. Note that <strong>only slots count toward playthrough</strong> for promotional redemptions.</p>',
 bonus_detail='<p>DimeSweeps daily bonuses are <strong>random</strong> in amount. The promotional calendar is the real engine — seasonal bonuses, holiday events, and reload offers give active players multiple earn opportunities throughout the month beyond the daily login reward.</p>',
 payout_detail='<p>Minimum redemption at DimeSweeps is <strong>$100 SC</strong> for both cash and crypto. Complete KYC verification first. Processing takes <strong>3–5 business days</strong> for cash; crypto is typically faster.</p>',
 faqs=[
  ('Is DimeSweeps legit?','Yes. DimeSweeps is a Delaware-regulated sweepstakes casino operating as part of the SpeedSweeps family since 2023.'),
  ('Is DimeSweeps related to SpeedSweeps?','Yes. DimeSweeps is a sister site that shares infrastructure, games, and payment systems with SpeedSweeps, RichSweeps, and SweepsRoyal.'),
  ('What is the minimum payout at DimeSweeps?','$100 SC for both cash and crypto redemptions.'),
  ('Does DimeSweeps support crypto payouts?','Yes — both Bitcoin and cash redemptions are available at $100 minimum.'),
  ('Is DimeSweeps available in Canada?','No, US only.'),
  ('What is the daily bonus at DimeSweeps?','Random — varies each day rather than being a fixed SC amount.'),
 ]
),

# 3. RICHSWEEPS
dict(
 slug='richsweeps', name='RichSweeps', score='4.1', tier='High Tier',
 site_url='https://www.richsweeps.com', affiliate='https://richsweeps.com/?ref=r_poponline63',
 parent='SpeedSweeps family (Delaware)', launch='2023', age='18+',
 daily='Random daily bonus', welcome='Welcome offer on signup',
 min_redeem='$100 SC (cash)', payout_speed='3–5 business days',
 games='1,000+', r_games='4.2', r_bonus='4.0', r_payout='4.1',
 restricted=['ID','WA','MT','MI','NV','KY'],
 title='RichSweeps Casino Review 2026 — Legit? Daily Bonus, Payouts & Rating',
 meta_desc='RichSweeps review 2026: 4.1/5. SpeedSweeps family, Delaware-regulated. 1,000+ games, frequent promos, $100 min cash payout. Is RichSweeps legit? Full honest review.',
 keywords='richsweeps review, is richsweeps legit, richsweeps daily bonus, richsweeps payout, richsweeps promo code 2026',
 h1='RichSweeps Review 2026: <span class="highlight">Solid High Tier Performer</span>',
 verdict='RichSweeps is a strong High Tier sweepstakes casino built on the Delaware-regulated SpeedSweeps infrastructure. Its game library is one of the better ones in the family, and high promotional frequency means active players earn well. Cash-only redemptions (no crypto) and a $100 minimum are the main drawbacks.',
 schema_body='RichSweeps is a Delaware-regulated sweepstakes casino from the SpeedSweeps family with 1,000+ games, high promo frequency, and $100 minimum cash redemptions.',
 what_is='<p>RichSweeps is a <strong>SpeedSweeps family member</strong>, sharing the same Delaware regulatory foundation and core infrastructure as SpeedSweeps, DimeSweeps, and SweepsRoyal. It differentiates itself with what reviewers call <strong>"one of the better game libraries in the family"</strong> — a curated selection focused on quality over sheer quantity.</p><p>For multi-platform farmers, RichSweeps adds another high-frequency promo calendar to the rotation. Since each family site operates independently with its own promotions, stacking SpeedSweeps + DimeSweeps + RichSweeps gives players three parallel earning channels.</p>',
 promo='<p>RichSweeps provides a <strong>welcome offer</strong> for new registrations — check the site for the current package. The platform runs <strong>HIGH promotional frequency</strong> with regular events, reload bonuses, and social media giveaways throughout the month.</p>',
 steps=['Go to <a href="https://richsweeps.com/?ref=r_poponline63" target="_blank" rel="noopener">richsweeps.com</a> and sign up.','Verify your email to activate your account.','Claim your welcome package from the promotions page.','Explore the 1,000+ game library.','Follow their social channels to catch bonus giveaways.'],
 pros=['SpeedSweeps family — Delaware-regulated and established','1,000+ quality game selection','HIGH promotional frequency','VIP loyalty program included','$100 cash redemption minimum','Well-curated game catalog within the family'],
 cons=['Cash redemption only — no crypto option','Random daily bonus structure','Only slots count toward playthrough','No gift card redemptions','$100 minimum redemption','Canada not available'],
 games_detail='<p>RichSweeps boasts <strong>1,000+ games</strong> with what reviewers consider the strongest curation of the SpeedSweeps family. Slots span all volatility levels with recognizable mechanics. Table games and specialty titles round out the catalog. New titles added regularly.</p>',
 bonus_detail='<p>Like its sister sites, RichSweeps runs a <strong>random daily bonus</strong> — no fixed SC per login. The strength is the <strong>HIGH promo calendar</strong>: seasonal events, reload bonuses, and email promotions that reward active players consistently across the month.</p>',
 payout_detail='<p>RichSweeps requires <strong>$100 SC</strong> minimum for cash redemptions. No crypto option (unlike SpeedSweeps and DimeSweeps). Complete KYC before submitting. Processing takes <strong>3–5 business days</strong>.</p>',
 faqs=[
  ('Is RichSweeps legit?','Yes. RichSweeps is Delaware-regulated and operates under the SpeedSweeps family infrastructure since 2023.'),
  ('Does RichSweeps support crypto payouts?','No. RichSweeps is cash-only. For crypto, use SpeedSweeps or DimeSweeps from the same family.'),
  ('What is the daily bonus at RichSweeps?','A random daily bonus — the amount varies each login day.'),
  ('Is RichSweeps part of SpeedSweeps?','Yes — RichSweeps, DimeSweeps, SweepsRoyal, and SpeedSweeps are all part of the same Delaware-based family.'),
  ('What is the minimum payout at RichSweeps?','$100 SC for cash redemptions.'),
  ('Can Canadians use RichSweeps?','No. RichSweeps is US only.'),
 ]
),

# 4. SWEEPSROYAL
dict(
 slug='sweepsroyal', name='SweepsRoyal', score='4.2', tier='High Tier',
 site_url='https://www.sweepsroyal.com', affiliate='https://sweepsroyal.com/?ref=r_poponline63',
 parent='SpeedSweeps family (Delaware)', launch='2023', age='18+',
 daily='Random daily bonus', welcome='Welcome offer on signup',
 min_redeem='$100 SC (cash) / $100 SC (crypto)', payout_speed='Near-instant processing',
 games='1,100+', r_games='4.2', r_bonus='4.1', r_payout='4.5',
 restricted=['ID','WA','MT','MI','NV','KY'],
 title='SweepsRoyal Casino Review 2026 — Near-Instant Payouts & High Tier Rating',
 meta_desc='SweepsRoyal review 2026: 4.2/5. SpeedSweeps family standout — near-instant payouts, 1,100+ games, cash & crypto. Is SweepsRoyal legit? Full honest review for 2026.',
 keywords='sweepsroyal review, is sweepsroyal legit, sweepsroyal daily bonus, sweepsroyal payout speed, sweepsroyal promo 2026',
 h1='SweepsRoyal Review 2026: <span class="highlight">Near-Instant Payouts Stand Out</span>',
 verdict='SweepsRoyal is the payout speed leader of the SpeedSweeps family. Its near-instant redemption processing is genuinely impressive for the sweepstakes space — most competitors take 3–10 days. Combined with 1,100+ games, dual cash and crypto, and high promo frequency, SweepsRoyal earns a strong High Tier position.',
 schema_body='SweepsRoyal is a Delaware-regulated sweepstakes casino known for near-instant payout processing, 1,100+ games, and dual cash and crypto redemptions at $100 minimum.',
 what_is='<p>SweepsRoyal is a <strong>SpeedSweeps family member</strong> with one defining advantage over its siblings: <strong>near-instant payout processing</strong>. While most sweepstakes casinos take 3–10 business days to process redemptions, SweepsRoyal users report same-day or next-day processing in most cases.</p><p>Built on Delaware-regulated infrastructure, SweepsRoyal offers <strong>1,100+ games</strong>, dual cash and crypto redemption, and the same high-frequency promotional calendar shared across the family. For players who prioritize getting paid fast, SweepsRoyal is the clear choice in the SpeedSweeps ecosystem.</p>',
 promo='<p>SweepsRoyal offers a <strong>welcome package</strong> for new accounts. Visit the promotions page to see the current offer. The platform runs frequent seasonal events, reload bonuses, and social media giveaways that keep active players earning throughout the month.</p>',
 steps=['Go to <a href="https://sweepsroyal.com/?ref=r_poponline63" target="_blank" rel="noopener">sweepsroyal.com</a> and register.','Verify your email to activate your account.','Claim your welcome offer from the promotions page.','Complete KYC verification to enable fast payouts.','Make your first redemption and experience the near-instant processing.'],
 pros=['Near-instant payout processing — standout in sweepstakes space','SpeedSweeps family — Delaware-regulated and proven','1,100+ game library','Cash AND crypto redemptions at $100 each','HIGH promotional frequency','VIP program included'],
 cons=['Random daily bonus — not predictable','Only slots count toward playthrough','$100 minimum on all redemptions','No gift card option','Canada not available'],
 games_detail='<p>SweepsRoyal offers <strong>1,100+ games</strong> from the SpeedSweeps shared catalog. Slots are the main attraction with all volatility levels covered. Table games and specialty titles fill out the library. Regular new additions keep the catalog current.</p>',
 bonus_detail='<p>Daily bonuses are <strong>random</strong> in amount — same structure as the other SpeedSweeps family members. The standout is the <strong>promotional calendar</strong> with high frequency events, plus the fact that your earnings reach your account faster than virtually any competitor.</p>',
 payout_detail='<p>SweepsRoyal requires <strong>$100 SC</strong> minimum for both cash and crypto redemptions. Complete KYC verification before submitting your first request. The key differentiator is processing speed: <strong>near-instant</strong> in most cases — significantly faster than the 3–10 day industry standard.</p>',
 faqs=[
  ('Is SweepsRoyal legit?','Yes. SweepsRoyal is Delaware-regulated as part of the SpeedSweeps family and has a strong payout track record.'),
  ('How fast are SweepsRoyal payouts?','Near-instant in most cases — a standout feature compared to the 3–10 days typical at other sweepstakes casinos.'),
  ('Does SweepsRoyal have crypto payouts?','Yes — both cash and crypto redemptions are available at $100 minimum each.'),
  ('Is SweepsRoyal part of SpeedSweeps?','Yes. SweepsRoyal, DimeSweeps, RichSweeps, and SpeedSweeps are all from the same Delaware-based family.'),
  ('What is the minimum redemption at SweepsRoyal?','$100 SC for both cash and cryptocurrency.'),
  ('Is SweepsRoyal available in Canada?','No. US only.'),
 ]
),

# 5. SPINBLITZ
dict(
 slug='spinblitz', name='SpinBlitz', score='4.3', tier='High Tier',
 site_url='https://affiliates.routy.app/route/114426?affId=3353&ts=5005447', affiliate='https://affiliates.routy.app/route/114426?affId=3353&ts=5005447',
 parent='B2 Group (Isle of Man)', launch='2024', age='18+',
 daily='$1 SC/day', welcome='$10 gift card bonus on signup',
 min_redeem='$10 SC (gift cards) / $50 SC (cash)', payout_speed='2–5 business days',
 games='800+', r_games='4.2', r_bonus='4.3', r_payout='4.3',
 restricted=['ID','WA','MT','MI','NV','CT'],
 title='SpinBlitz Casino Review 2026 — Legit? $1 Daily SC, Low Minimums & Rating',
 meta_desc='SpinBlitz review 2026: 4.3/5. B2 Group (McLuck family). $1 SC daily, $10 gift card minimum, 800+ games. Is SpinBlitz legit? Full honest review for US sweepstakes players.',
 keywords='spinblitz review, is spinblitz legit, spinblitz daily bonus, spinblitz payout, spinblitz promo code 2026',
 h1='SpinBlitz Review 2026: <span class="highlight">McLuck Clone with Low Redemption Floors</span>',
 verdict='SpinBlitz is a B2 Group platform — same Isle of Man infrastructure as McLuck. The $1 SC daily bonus, $10 gift card minimum, and $50 cash minimum make it one of the more accessible entry points in the High Tier. HIGH promotional frequency and the full McLuck game library round out a strong value proposition.',
 schema_body='SpinBlitz is a B2 Group sweepstakes casino offering $1 SC daily, $10 gift card minimum redemption, $50 cash minimum, 800+ games, and high promotional frequency.',
 what_is='<p>SpinBlitz runs on the <strong>B2 Group infrastructure</strong> — the same Isle of Man-licensed platform behind McLuck, MegaBonanza, PlayFame, and Jackpota. It was formerly known as <strong>Scratchful</strong> before rebranding in 2024, and it carries the full McLuck game library to a new audience.</p><p>The platform\'s best feature is <strong>accessibility</strong>: the <strong>$10 gift card minimum</strong> is among the lowest in the High Tier, and the <strong>$50 cash minimum</strong> (vs. $100 at most competitors) means players reach their first payout faster. Combined with a <strong>$1 SC daily bonus</strong>, SpinBlitz rewards consistent players quickly.</p>',
 promo='<p>SpinBlitz provides a <strong>$10 gift card bonus</strong> for new accounts on signup. The platform also runs <strong>HIGH promotional frequency</strong> with seasonal events, reload bonuses, and regular giveaways — a benefit of the established B2 infrastructure.</p>',
 steps=['Visit <a href="https://affiliates.routy.app/route/114426?affId=3353&ts=5005447" target="_blank" rel="noopener">SpinBlitz</a> and create an account.','Verify your email to unlock your signup bonus.','Collect your daily $1 SC each login.','Use the promo page for additional earn opportunities.','Reach $10 SC for a gift card or $50 SC for cash payout.'],
 pros=['$1 SC daily bonus — predictable daily earning','$10 gift card minimum — lowest floor in High Tier','$50 cash minimum — faster to first payout','B2 Group infrastructure — Isle of Man licensed and proven','800+ game library (full McLuck catalog)','HIGH promotional frequency'],
 cons=['No VIP loyalty program','Not farmable for bonus stacking','No cryptocurrency redemption','Canada not available','Rebranded identity (formerly Scratchful) — less established name recognition'],
 games_detail='<p>SpinBlitz shares the <strong>B2 Group game library</strong> — over <strong>800 titles</strong> across slots, table games, and specialty games. The catalog matches what McLuck offers, spanning all volatility levels with regular new additions from B2\'s software partnerships. Strong mobile performance.</p>',
 bonus_detail='<p>SpinBlitz provides a fixed <strong>$1 SC daily bonus</strong> on login — one of the most consistent daily earners in the High Tier. Combined with the <strong>HIGH promotional frequency</strong> and the low $10 gift card floor, players can reach their first redemption faster here than at most $100-minimum competitors.</p>',
 payout_detail='<p>SpinBlitz offers the lowest redemption minimums in the B2 family: <strong>$10 SC for gift cards</strong> and <strong>$50 SC for cash</strong>. Complete identity verification (KYC) in your account settings. Processing takes <strong>2–5 business days</strong>.</p>',
 faqs=[
  ('Is SpinBlitz legit?','Yes. SpinBlitz operates on B2 Group infrastructure (Isle of Man licensed), the same platform behind McLuck. Legitimate with a solid payout track record.'),
  ('What is the daily bonus at SpinBlitz?','$1 SC daily on login — a fixed, predictable amount.'),
  ('What is the minimum payout at SpinBlitz?','$10 SC for gift cards and $50 SC for cash redemptions.'),
  ('Is SpinBlitz related to McLuck?','Yes. SpinBlitz is built on B2 Group infrastructure alongside McLuck, MegaBonanza, PlayFame, and Jackpota.'),
  ('Was SpinBlitz formerly called something else?','Yes — SpinBlitz was previously called Scratchful before rebranding.'),
  ('Is SpinBlitz available in Canada?','No. US only.'),
 ]
),

# 6. AMERICAN LUCK
dict(
 slug='american-luck', name='American Luck', score='4.1', tier='High Tier',
 site_url='https://americanluck.com', affiliate='https://americanluck.com/signup/90a4a8d4-856c-46e8-b853-26c91db2051e',
 parent='PriorityPlay (Wyoming)', launch='2024', age='18+',
 daily='HIGH daily SC bonus', welcome='Welcome package on signup',
 min_redeem='$100 SC (cash)', payout_speed='3–5 business days',
 games='600+', r_games='4.0', r_bonus='4.2', r_payout='4.1',
 restricted=['ID','WA','MT','MI','NV','CT'],
 title='American Luck Casino Review 2026 — Legit? Daily Bonus & Payouts',
 meta_desc='American Luck review 2026: 4.1/5. PriorityPlay infrastructure (Zula/Sportzino family). HIGH daily SC, VIP program, Wyoming-regulated. Is American Luck legit? Full review.',
 keywords='american luck casino review, is american luck legit, american luck daily bonus, american luck payout, american luck promo 2026',
 h1='American Luck Review 2026: <span class="highlight">PriorityPlay Platform with High Daily SC</span>',
 verdict='American Luck runs on the PriorityPlay infrastructure — the same proven backend behind Zula Casino, Fortune Coins, and Sportzino. The HIGH daily SC bonus and included VIP program give it a strong value proposition for the High Tier. Wyoming-regulated and built on established rails, it\'s a reliable newer addition to the PriorityPlay family.',
 schema_body='American Luck is a Wyoming-regulated sweepstakes casino on PriorityPlay infrastructure (Zula/Sportzino family), offering a high daily SC bonus, VIP program, and $100 cash minimum redemption.',
 what_is='<p>American Luck launched in 2024 as the newest member of the <strong>PriorityPlay family</strong> — the Wyoming-regulated platform behind Zula Casino, Fortune Coins, and Sportzino. It shares the same proven backend infrastructure, game library, and payment systems as its established siblings.</p><p>The platform\'s headline feature is a <strong>HIGH daily SC bonus</strong> — one of the better consistent daily earners in the newer High Tier platforms. Combined with an included <strong>VIP program</strong> and good game selection at launch, American Luck has quickly positioned itself as a worthwhile addition to any multi-platform rotation.</p>',
 promo='<p>American Luck provides a <strong>welcome package</strong> for new accounts. Check the site for the current offer. The platform\'s strength is the <strong>HIGH daily SC bonus</strong> — farmable and consistent, making it well-suited for daily rotation.</p>',
 steps=['Visit <a href="https://americanluck.com/signup/90a4a8d4-856c-46e8-b853-26c91db2051e" target="_blank" rel="noopener">americanluck.com</a> and sign up.','Verify your email and complete profile setup.','Claim your welcome package from the bonuses page.','Collect the HIGH daily SC bonus each login.','Work through the VIP tiers for escalating rewards.'],
 pros=['HIGH daily SC bonus — farmable and consistent','PriorityPlay infrastructure — same backend as Zula and Sportzino','VIP program with tiered rewards','Wyoming-regulated operator','Good game selection at launch','Sister to Fortune Coins and Sportzino'],
 cons=['New platform — shorter track record','Medium promotional frequency outside daily bonus','No gift card or crypto redemption options','$100 minimum cash withdrawal','Canada not available'],
 games_detail='<p>American Luck carries <strong>600+ games</strong> from the PriorityPlay catalog, sharing providers with Zula, Fortune Coins, and Sportzino. Strong slot selection across all volatility levels. Table game coverage includes blackjack, roulette, and poker variants. Regular new additions from established software partners.</p>',
 bonus_detail='<p>The standout is the <strong>HIGH daily SC bonus</strong> — credited consistently on login, making American Luck a reliable farming platform. The PriorityPlay infrastructure means bonus crediting and tracking is proven and reliable. VIP progression adds a second earn layer for active players.</p>',
 payout_detail='<p>American Luck requires <strong>$100 SC</strong> minimum for cash redemptions. No gift card or crypto option. Complete KYC verification in account settings before submitting. Processing takes <strong>3–5 business days</strong>.</p>',
 faqs=[
  ('Is American Luck legit?','Yes. American Luck is Wyoming-regulated and built on PriorityPlay infrastructure — the same backend behind Zula Casino and Sportzino.'),
  ('Is American Luck related to Zula Casino?','Yes. American Luck, Zula, Fortune Coins, and Sportzino are all PriorityPlay family sites sharing the same infrastructure.'),
  ('What is the daily bonus at American Luck?','A HIGH daily SC bonus credited on login — one of the better consistent daily earners in the newer High Tier platforms.'),
  ('What is the minimum payout at American Luck?','$100 SC for cash redemptions.'),
  ('Does American Luck support crypto payouts?','No. Cash redemption only at $100 minimum.'),
  ('Is American Luck available in Canada?','No. US only.'),
 ]
),

# 7. FORTUNEWHEELZ
dict(
 slug='fortunewheelz', name='FortuneWheelz', score='3.8', tier='Mid Tier',
 site_url='https://fortunewheelz.com', affiliate='https://fortunewheelz.com/lobby/?invited_by=97XS6G',
 parent='A1 Development LLC (Wyoming)', launch='2022', age='18+',
 daily='Login bonus available', welcome='250,000 Gold Coins free on signup',
 min_redeem='$100 FC (cash via PayPal)', payout_speed='Instant–7 days (PayPal)',
 games='1,300+', r_games='3.9', r_bonus='3.8', r_payout='3.8',
 restricted=['CA','CT','DE','ID','LA','MI','MT','NV','NJ','NY','RI','TN','WA','WV','WY'],
 title='FortuneWheelz Casino Review 2026 — Legit? PayPal Payouts, Bonuses & Rating',
 meta_desc='FortuneWheelz review 2026: 3.8/5. 1,300+ games, 250K Gold Coins free, PayPal payouts, $100 FC min, available in 35 states. Is FortuneWheelz legit? Full honest review.',
 keywords='fortunewheelz review, is fortunewheelz legit, fortunewheelz daily bonus, fortunewheelz paypal payout, fortunewheelz promo code 2026',
 h1='FortuneWheelz Review 2026: <span class="highlight">PayPal Payouts & 1,300+ Games</span>',
 verdict='FortuneWheelz stands out for two things: a massive 250,000 Gold Coin welcome offer and PayPal support for both purchases and payouts — a rarity in sweepstakes casinos. The 1,300+ game library is solid. The main limitation is restricted state availability (15 states blocked) and a $100 FC minimum that\'s steep for newer players.',
 schema_body='FortuneWheelz is a sweepstakes casino by A1 Development LLC offering 1,300+ games, 250,000 Gold Coins free on signup, PayPal payouts, and $100 FC minimum redemption.',
 what_is='<p>FortuneWheelz is operated by <strong>A1 Development LLC</strong> (Wyoming) — the same company behind FunzCity. Launched in 2022, it has built a reputation for its <strong>generous Gold Coin welcome offer</strong> and, most notably, <strong>PayPal support</strong> for both deposits and redemptions.</p><p>PayPal availability is rare in the sweepstakes casino space. It enables faster, more familiar transactions for players already in the PayPal ecosystem. Redemptions can process instantly to 7 days depending on the method, versus the 7–10 day ACH standard elsewhere.</p><p>The <strong>1,300+ game library</strong> is one of the larger catalogs in the Mid Tier, and the <strong>1× playthrough requirement</strong> (sweepstakes coins) is significantly more lenient than the 3–5× typical at competitors.</p>',
 promo='<p>New FortuneWheelz accounts receive <strong>250,000 Gold Coins free</strong> on signup — no purchase required. This is among the largest GC welcome offers in the sweepstakes space. Additionally, promo codes from review sites can unlock enhanced packages including bonus Fortune Coins.</p>',
 steps=['Visit <a href="https://fortunewheelz.com/lobby/?invited_by=97XS6G" target="_blank" rel="noopener">fortunewheelz.com</a> and register.','Complete email verification to receive 250,000 Gold Coins.','Connect PayPal for easier deposits and faster redemptions.','Explore the 1,300+ game library.','Accumulate 100 Fortune Coins to make your first cash redemption.'],
 pros=['250,000 Gold Coins free on signup — among the largest welcome offers','PayPal support for purchases AND redemptions — rare in sweepstakes','1,300+ game library — solid selection','1× playthrough on sweepstakes coins — far below industry average','Wyoming-based legitimate operator (A1 Development LLC)','Regular login bonuses and promo events'],
 cons=['15 states blocked — significant availability gap','$100 FC minimum for cash redemption — steep for new players','No VIP program','No crypto redemption option','Limited table game selection (slots-dominant)','Trustpilot reviews mixed'],
 games_detail='<p>FortuneWheelz carries <strong>1,300+ games</strong> making it one of the larger Mid Tier catalogs. Slots dominate with titles spanning classic, video, and jackpot formats. Live game integration has expanded through Iconic21 partnership. Note: table game selection is more limited compared to God Tier platforms.</p>',
 bonus_detail='<p>The headline offer is <strong>250,000 Gold Coins free on signup</strong> — no purchase needed. Daily login bonuses add ongoing Gold Coins. The <strong>1× playthrough</strong> on sweepstakes coins is a significant advantage: most platforms require 3–5× before you can redeem. At FortuneWheelz, you reach payout eligibility much faster.</p>',
 payout_detail='<p>FortuneWheelz requires <strong>$100 Fortune Coins (FC)</strong> minimum for cash redemptions. The standout is <strong>PayPal support</strong> — enabling instant to 7-day processing vs. the 7–10 day ACH norm. Connect your PayPal in account settings. Standard ACH bank transfer is also available.</p>',
 faqs=[
  ('Is FortuneWheelz legit?','Yes. FortuneWheelz is operated by A1 Development LLC (Wyoming) and has been paying out players since 2022.'),
  ('Does FortuneWheelz support PayPal?','Yes — PayPal is available for both purchases and cash redemptions, which is rare in the sweepstakes casino space.'),
  ('What states is FortuneWheelz not available in?','CA, CT, DE, ID, LA, MI, MT, NV, NJ, NY, RI, TN, WA, WV, and WY — 15 states total.'),
  ('What is the welcome bonus at FortuneWheelz?','250,000 Gold Coins free on signup, no purchase required.'),
  ('What is the minimum cash out at FortuneWheelz?','$100 Fortune Coins for cash redemption.'),
  ('Is FortuneWheelz related to FunzCity?','Yes — both are operated by A1 Development LLC out of Wyoming.'),
 ]
),

# 8. FUNZCITY
dict(
 slug='funzcity', name='FunzCity', score='3.6', tier='Mid Tier',
 site_url='https://funzcity.com', affiliate='http://funzcity.com/?invited_by=Z1Y2ZX',
 parent='A1 Development LLC (Wyoming)', launch='2021', age='18+',
 daily='20 Coin Cash (CC) daily login bonus', welcome='125,000 Fun Coins + first purchase 750K FC / $24.99',
 min_redeem='$100 CC (cash)', payout_speed='5–10 business days',
 games='1,750+', r_games='4.0', r_bonus='3.6', r_payout='3.4',
 restricted=['CA','CT','DE','ID','LA','MI','MT','NV','NJ','NY','RI','TN','WA','WV','WY'],
 title='FunzCity Casino Review 2026 — Legit? Daily Bonus, Payouts & Rating',
 meta_desc='FunzCity review 2026: 3.6/5. 1,750+ games, 20 CC daily login, 125K Fun Coins signup. A1 Development (Wyoming). Is FunzCity legit? Full honest review for US players.',
 keywords='funzcity review, is funzcity legit, funzcity daily bonus, funzcity payout, funzcity promo code 2026',
 h1='FunzCity Review 2026: <span class="highlight">1,750+ Games, Daily CC Bonus</span>',
 verdict='FunzCity has one of the largest game libraries in the Mid Tier at 1,750+ titles and provides a consistent 20 Coin Cash daily login bonus. However, the $100 minimum redemption is steep and Trustpilot reviews are mixed. Operated by A1 Development LLC (FortuneWheelz\'s parent), it benefits from established infrastructure but needs more polish on the player experience side.',
 schema_body='FunzCity is a sweepstakes casino by A1 Development LLC with 1,750+ games, 20 Coin Cash daily login bonus, 125,000 Fun Coins free signup, and $100 CC minimum cash redemption.',
 what_is='<p>FunzCity is operated by <strong>A1 Development LLC</strong> (Wyoming), the same company behind FortuneWheelz. Launched in 2021, it\'s one of the older entries in the A1 portfolio and has grown its game library to an impressive <strong>1,750+ titles</strong> — one of the largest catalogs in the Mid Tier.</p><p>The platform offers a <strong>20 Coin Cash (CC) daily login bonus</strong> — notable because CC is the redeemable currency, meaning every daily login directly earns toward your payout. For reference, many platforms give daily GC (not redeemable) rather than CC.</p><p>The game library expanded through an <strong>Iconic21 live game integration</strong>, adding live dealer titles to what was previously a slots-only catalog. No table games in the traditional sense though — blackjack and roulette are limited to the live section.</p>',
 promo='<p>New FunzCity accounts receive <strong>125,000 Fun Coins free</strong> on signup — no purchase required. The first purchase bonus is <strong>750,000 Fun Coins + 50 Coin Cash</strong> for $24.99. The daily login provides <strong>20 Coin Cash</strong> — directly redeemable currency credited every day.</p>',
 steps=['Go to <a href="http://funzcity.com/?invited_by=Z1Y2ZX" target="_blank" rel="noopener">funzcity.com</a> and create your account.','Verify your email to receive 125,000 Fun Coins.','Log in daily to collect 20 Coin Cash.','Explore the 1,750+ game library.','Accumulate $100 CC to make your first cash redemption.'],
 pros=['1,750+ game library — one of the largest in Mid Tier','20 CC daily login bonus — directly redeemable currency','125,000 Fun Coins free on signup','Live game integration via Iconic21','Operated by established A1 Development LLC','Available in 40 US states'],
 cons=['$100 CC minimum redemption is steep','Mixed Trustpilot reviews','No traditional table games (blackjack/roulette not in main lobby)','5–10 day payout processing — slower than competitors','15 states blocked — same as FortuneWheelz','No VIP program','No crypto redemption'],
 games_detail='<p>FunzCity leads the Mid Tier in catalog size with <strong>1,750+ titles</strong>. Slots dominate with all variance levels and multiple software providers. The Iconic21 integration adds live dealer titles. Note: classic table games (non-live blackjack, roulette) are limited — if you want deep table game coverage, High Tier platforms serve better.</p>',
 bonus_detail='<p>The <strong>20 Coin Cash daily login bonus</strong> is notable because CC is directly redeemable — every login directly builds toward your $100 payout floor. At 20 CC/day, 5 days of play equals $1 redeemable value. To reach $100 purely through daily logins takes 500 days — so combining with gameplay, promos, and the purchase bonus is recommended for faster progression.</p>',
 payout_detail='<p>FunzCity requires <strong>$100 Coin Cash (CC)</strong> minimum for cash redemption. Complete KYC identity verification in your account profile before submitting a withdrawal. Processing takes <strong>5–10 business days</strong> — slower than most competitors. PayPal is not available here (use FortuneWheelz for PayPal).</p>',
 faqs=[
  ('Is FunzCity legit?','FunzCity is a legitimate sweepstakes casino by A1 Development LLC (Wyoming). It has been operating since 2021. Reviews are mixed — most complaints focus on slow payouts.'),
  ('What is the daily bonus at FunzCity?','20 Coin Cash per day on login — directly redeemable currency.'),
  ('What is the minimum payout at FunzCity?','$100 Coin Cash for cash redemption.'),
  ('Is FunzCity related to FortuneWheelz?','Yes — both are operated by A1 Development LLC out of Wyoming.'),
  ('How long do FunzCity payouts take?','5–10 business days — slower than most competitors. Plan accordingly.'),
  ('What states is FunzCity not available in?','CA, CT, DE, ID, LA, MI, MT, NV, NJ, NY, RI, TN, WA, WV, and WY.'),
 ]
),

# 9. LEGENDZ
dict(
 slug='legendz', name='Legendz', score='3.8', tier='Mid Tier',
 site_url='https://legendz.com', affiliate='https://affiliates.routy.app/route/91174?affId=3353&ts=5005447',
 parent='Legendz Ltd (Cyprus)', launch='2022', age='18+',
 daily='High daily SC bonus (purchase-linked)', welcome='Welcome offer on signup',
 min_redeem='$10 SC (gift cards) / $100 SC (cash)', payout_speed='Instant processing',
 games='1,500+', r_games='4.0', r_bonus='3.6', r_payout='4.2',
 restricted=['ID','WA','MT','MI','NV','CT','DE'],
 title='Legendz Casino Review 2026 — Legit? Instant Payouts, Daily Bonus & Rating',
 meta_desc='Legendz review 2026: 3.8/5. Cyprus-licensed, instant redemptions, $10 gift card minimum, 1,500+ games, VIP program. Is Legendz legit? Full honest review for US players.',
 keywords='legendz casino review, is legendz legit, legendz daily bonus, legendz payout, legendz promo code 2026',
 h1='Legendz Review 2026: <span class="highlight">Instant Payouts & 1,500+ Games</span>',
 verdict='Legendz earns its Mid Tier placement through instant redemption processing and a low $10 gift card minimum — standout features for speed-focused players. The 1,500+ game library and VIP program add depth. The main catches: the high daily bonus rate requires pack purchases to maintain, and Cyprus licensing is less rigorous than US-regulated competitors.',
 schema_body='Legendz is a Cyprus-licensed sweepstakes casino with 1,500+ games, instant payout processing, $10 gift card and $100 cash minimums, and an included VIP program.',
 what_is='<p>Legendz is operated by <strong>Legendz Ltd</strong>, a Cyprus-based company — one of the few sweepstakes casinos with non-US licensing. It launched in 2022 targeting the US sweepstakes market with a <strong>1,500+ game library</strong> and two defining features: <strong>instant payout processing</strong> and a <strong>$10 gift card minimum</strong>.</p><p>The platform\'s VIP program rewards active players with escalating perks, and the game catalog is genuinely large for a Mid Tier platform. The caveat on the daily bonus: the HIGH rate is tied to <strong>pack purchases</strong> — free-play-only accounts earn at a lower rate. For pure free players, the earning pace is more modest than it appears on marketing materials.</p>',
 promo='<p>Legendz provides a <strong>welcome offer</strong> for new accounts. Check the promotions page for the current package. The VIP program begins from day one, with points earned on all play contributing to tier advancement.</p>',
 steps=['Visit <a href="https://affiliates.routy.app/route/91174?affId=3353&ts=5005447" target="_blank" rel="noopener">legendz.com</a> and create an account.','Verify email and complete registration.','Claim your welcome offer from the bonuses section.','Enroll in the VIP program to start earning tier points.','Reach $10 SC for a gift card or $100 SC for cash payout.'],
 pros=['Instant payout processing — fastest in Mid Tier','$10 gift card minimum — accessible first redemption','1,500+ game library — large for a Mid Tier platform','VIP program included from day one','Cyprus licensed — legitimate international operator','Slots and table games covered'],
 cons=['HIGH daily SC rate requires pack purchases to maintain','$100 minimum for cash redemption','No crypto redemption option','Cyprus licensing less rigorous than US-regulated platforms','US-only availability','Not easily farmable at high rates without spending'],
 games_detail='<p>Legendz carries <strong>1,500+ games</strong> — one of the largest libraries in the Mid Tier. Coverage spans slots (all variance levels), table games (blackjack, roulette, baccarat), video poker, and specialty games. Game quality is generally strong with recognizable mechanics and smooth mobile performance.</p>',
 bonus_detail='<p>Legendz advertises a HIGH daily SC rate, but the fine print matters: the highest tier requires <strong>pack purchases</strong> to sustain. Free-play-only accounts receive a more modest daily credit. The VIP program provides a secondary earning layer — points accumulate toward tier bonuses and exclusive rewards.</p>',
 payout_detail='<p>Legendz offers two redemption tiers: <strong>$10 SC for gift cards</strong> (instant) and <strong>$100 SC for cash</strong> (also instant processing). The instant processing is a genuine differentiator — most competitors take 3–10 days. Complete KYC verification to enable withdrawals.</p>',
 faqs=[
  ('Is Legendz legit?','Yes. Legendz is a legitimate sweepstakes casino operated by Legendz Ltd (Cyprus) since 2022 with a consistent payout track record.'),
  ('How fast are Legendz payouts?','Instant processing — both gift card and cash redemptions are processed immediately upon approval.'),
  ('What is the minimum payout at Legendz?','$10 SC for gift cards and $100 SC for cash redemptions.'),
  ('Does the high daily bonus require purchases?','Yes. The HIGH daily SC rate at Legendz is linked to pack purchases — free-play accounts earn at a lower rate.'),
  ('Does Legendz have a VIP program?','Yes — the VIP program starts from day one with points earned on all activity.'),
  ('Is Legendz available in Canada?','No. US only.'),
 ]
),

# 10. SIDEPOT
dict(
 slug='sidepot', name='Sidepot', score='3.7', tier='Mid Tier',
 site_url='https://sidepot.us', affiliate='https://sidepot.us/home',
 parent='Fliff Inc (Pennsylvania)', launch='2023', age='18+',
 daily='Daily login bonus available', welcome='Welcome offer on signup',
 min_redeem='$100 SC (cash)', payout_speed='3–7 business days',
 games='500+', r_games='3.7', r_bonus='3.6', r_payout='3.8',
 restricted=['ID','WA','MT','MI','NV','CT','DE'],
 title='Sidepot Casino Review 2026 — Legit? Fliff Sister, Daily Bonus & Payouts',
 meta_desc='Sidepot review 2026: 3.7/5. Fliff sister casino (Pennsylvania). 500+ games, daily login bonus, $100 cash min. Is Sidepot legit? Full honest review for US sweepstakes players.',
 keywords='sidepot casino review, is sidepot legit, sidepot daily bonus, sidepot payout, sidepot promo code 2026',
 h1='Sidepot Review 2026: <span class="highlight">Fliff\'s Casino Sister Site</span>',
 verdict='Sidepot is Fliff\'s casino arm — a Mid Tier platform built for Fliff users who want casino slots alongside sports picks. Good promotional events and an established operator (Fliff Inc, Pennsylvania) give it credibility. The $100 cash minimum and no VIP or crypto options keep it in the Mid Tier rather than High.',
 schema_body='Sidepot is a sweepstakes casino by Fliff Inc (Pennsylvania) with 500+ games, daily login bonus, $100 cash minimum, and good promotional events.',
 what_is='<p>Sidepot is the <strong>casino sister site to Fliff</strong> — the popular social sportsbook based in Pennsylvania. Launched in 2023, it targets Fliff\'s existing user base with a familiar interface and the same operator trustworthiness that has made Fliff one of the more respected social sportsbooks.</p><p>For existing Fliff users, Sidepot offers a natural extension: casino slots and table games alongside the sports picks they already enjoy. For new players, it\'s a Mid Tier sweepstakes casino with <strong>500+ games</strong>, decent promotional events, and the backing of an established US operator.</p>',
 promo='<p>Sidepot provides a <strong>welcome offer</strong> for new accounts. The platform runs <strong>good promotional events</strong> — seasonal campaigns, social media giveaways, and periodic reload bonuses that add value beyond the daily login.</p>',
 steps=['Visit <a href="https://sidepot.us/home" target="_blank" rel="noopener">sidepot.us</a> and register.','Verify your email to activate your account.','Claim your welcome offer from the promotions page.','Log in daily to collect your SC bonus.','Explore the 500+ game library.'],
 pros=['Fliff Inc backing — established and trustworthy operator','500+ game library with slots and table games','Good promotional events and seasonal campaigns','Daily login bonus for consistent SC earning','Familiar experience for Fliff users','Pennsylvania-based legitimate operator'],
 cons=['$100 cash minimum — no gift card option','No VIP loyalty program','No cryptocurrency redemption','Not farmable — limited bonus stacking','Canada not available','Smaller library than High Tier competitors'],
 games_detail='<p>Sidepot offers <strong>500+ games</strong> covering slots, table games, and specialty titles. The catalog uses the same underlying tech as Fliff, with smooth mobile performance and regular new game additions. Slot selection spans classic to video styles; table games cover blackjack, roulette, and poker variants.</p>',
 bonus_detail='<p>Sidepot\'s daily login bonus and promotional events are the main earning levers. The promotional calendar draws on Fliff\'s experience running regular player incentives — expect seasonal bonuses, leaderboard events, and occasional social media giveaways. Daily bonus amounts are modest but consistent.</p>',
 payout_detail='<p>Sidepot requires <strong>$100 SC</strong> minimum for cash redemption. No gift card or crypto options. Complete KYC identity verification in your account settings. Processing takes <strong>3–7 business days</strong> — standard for Mid Tier platforms.</p>',
 faqs=[
  ('Is Sidepot legit?','Yes. Sidepot is operated by Fliff Inc (Pennsylvania), a well-established social gaming company with a strong track record.'),
  ('Is Sidepot related to Fliff?','Yes — Sidepot is the casino sister site to Fliff social sportsbook, both operated by Fliff Inc.'),
  ('What is the minimum payout at Sidepot?','$100 SC for cash redemption. No gift card option.'),
  ('Does Sidepot have crypto payouts?','No. Cash redemption only.'),
  ('What is the daily bonus at Sidepot?','A daily login bonus is available — check the promotions page for current amounts.'),
  ('Is Sidepot available in Canada?','No. US only.'),
 ]
),

# 11. SPINQUEST
dict(
 slug='spinquest', name='SpinQuest', score='3.6', tier='Mid Tier',
 site_url='https://spinquest.com', affiliate='http://spinquest.com/?u=WXSBTAN',
 parent='SpinQuest LLC (California)', launch='2024', age='18+',
 daily='HIGH daily SC bonus', welcome='Decent welcome offer on signup',
 min_redeem='$100 SC (cash)', payout_speed='3–7 business days',
 games='300+', r_games='3.4', r_bonus='3.7', r_payout='3.6',
 restricted=['ID','WA','MT','MI','NV','CT','DE'],
 title='SpinQuest Casino Review 2026 — Legit? HIGH Daily Bonus & Payouts',
 meta_desc='SpinQuest review 2026: 3.6/5. California-based new platform. HIGH daily SC bonus, 300+ games, $100 cash min. Is SpinQuest legit? Full honest review for US sweepstakes players.',
 keywords='spinquest review, is spinquest legit, spinquest daily bonus, spinquest payout, spinquest promo code 2026',
 h1='SpinQuest Review 2026: <span class="highlight">High Daily SC on a New Platform</span>',
 verdict='SpinQuest is a new California-based platform with an impressive HIGH daily SC bonus as its headline feature. The 300+ game library is modest but growing, and the lack of VIP or crypto options puts it firmly in the Mid Tier. Worth adding for the daily SC alone, with the expectation that the platform will mature over time.',
 schema_body='SpinQuest is a California-based sweepstakes casino offering a high daily SC bonus, 300+ games, and $100 cash minimum redemption.',
 what_is='<p>SpinQuest launched in 2024 as a California-based sweepstakes casino with a clear hook: a <strong>HIGH daily SC bonus</strong> that reviewers have called "a standout for a new platform." It\'s the primary reason to add SpinQuest to your rotation — the daily earning rate punches above its weight class compared to more established platforms.</p><p>The trade-off is platform maturity. With a <strong>300+ game library</strong> that\'s growing but not yet deep, and no VIP program or crypto redemption, SpinQuest is clearly still building out. It\'s a good daily farming addition with the expectation that more features will be added as the platform develops.</p>',
 promo='<p>SpinQuest provides a <strong>welcome offer</strong> for new accounts alongside the HIGH daily SC bonus. Check the site for the current package. The welcome offer is described as providing "a solid entry point" for new players before settling into the daily earning rhythm.</p>',
 steps=['Go to <a href="http://spinquest.com/?u=WXSBTAN" target="_blank" rel="noopener">spinquest.com</a> and sign up.','Verify your email to activate your account.','Claim your welcome offer from the bonuses page.','Log in daily for the HIGH SC bonus.','Reach $100 SC for your first cash redemption.'],
 pros=['HIGH daily SC bonus — standout feature for a new platform','California-based operator — US regulated','Decent welcome offer for new players','Low-friction registration process','Platform has potential to improve as it grows'],
 cons=['300+ games — small library for the tier','No VIP loyalty program','No gift card or crypto redemption options','$100 minimum cash withdrawal','Limited promotional frequency beyond daily bonus','Short operational history — less established trust'],
 games_detail='<p>SpinQuest currently offers <strong>300+ games</strong> — a modest catalog that covers the core slot types and basic table games. The library is growing, and the California team has indicated regular additions are planned. For now, variety is the main limitation compared to platforms with 800–1,500+ titles.</p>',
 bonus_detail='<p>SpinQuest\'s HIGH daily SC bonus is the platform\'s strongest selling point. The rate is described as "a standout for a new platform" — meaning it competes favorably with more established casinos on daily earning alone. The welcome offer provides a meaningful entry boost. Promotional frequency beyond daily and welcome is currently medium.</p>',
 payout_detail='<p>SpinQuest requires <strong>$100 SC</strong> minimum for cash redemption. No gift card or crypto options currently. Complete identity verification in your account before submitting. Processing takes <strong>3–7 business days</strong>.</p>',
 faqs=[
  ('Is SpinQuest legit?','SpinQuest is a legitimate California-based sweepstakes casino launched in 2024. It is newer with a shorter track record — always a reasonable consideration for new platforms.'),
  ('What is the daily bonus at SpinQuest?','A HIGH daily SC bonus — one of the better daily earning rates among newer platforms.'),
  ('What is the minimum payout at SpinQuest?','$100 SC for cash redemption.'),
  ('Does SpinQuest have crypto payouts?','No. Cash redemption only at $100 minimum.'),
  ('Does SpinQuest have a VIP program?','No VIP program currently. Expected as the platform matures.'),
  ('Is SpinQuest available in Canada?','No. US only.'),
 ]
),

# 12. LUNALAND CASINO
dict(
 slug='lunaland', name='LunaLand Casino', score='3.7', tier='Mid Tier',
 site_url='https://lunalandcasino.com', affiliate='https://lunalandcasino.com/?inviter=9d8611a0-3ce7-5f54-a691-261bb2e300e2',
 parent='LunaLand LLC (Delaware)', launch='2023', age='18+',
 daily='LOW daily SC (farmable)', welcome='Great welcome package on signup',
 min_redeem='$50 SC (cash)', payout_speed='3–7 business days',
 games='800+', r_games='3.8', r_bonus='3.7', r_payout='3.6',
 restricted=['ID','WA','MT','MI','NV','CT'],
 title='LunaLand Casino Review 2026 — Legit? $50 Cash Min, Farmable Daily & Rating',
 meta_desc='LunaLand Casino review 2026: 3.7/5. Delaware-regulated, 800+ games, farmable daily SC, $50 cash minimum, VIP program. Is LunaLand legit? Full honest review 2026.',
 keywords='lunaland casino review, is lunaland legit, lunaland casino daily bonus, lunaland payout, lunaland promo code 2026',
 h1='LunaLand Casino Review 2026: <span class="highlight">Farmable Daily SC & Low Cash Floor</span>',
 verdict='LunaLand Casino earns its Mid Tier spot with a farmable daily SC structure, a welcome package that front-loads value, and a low $50 cash minimum — easier first redemption than most $100-floor competitors. The 800+ game library and included VIP program add depth. The low daily SC amount is the main limitation for high-volume farmers.',
 schema_body='LunaLand Casino is a Delaware-regulated sweepstakes casino with 800+ games, farmable daily SC, $50 cash minimum, and an included VIP program.',
 what_is='<p>LunaLand Casino launched in 2023 under <strong>Delaware regulation</strong> — a strong legal foundation for a newer platform. It has built its reputation on three things: a <strong>farmable daily SC structure</strong>, a <strong>generous welcome package</strong>, and one of the lower cash minimums in the Mid Tier at <strong>$50 SC</strong>.</p><p>The farmable daily bonus means the SC amount, while LOW, is <strong>consistent and predictable</strong>. Unlike random daily structures (SpeedSweeps family), LunaLand players know what to expect each login. The welcome package front-loads the most value, making the first month particularly rewarding.</p>',
 promo='<p>LunaLand provides a <strong>welcome package</strong> that reviewers describe as "great" for front-loading new player value. Combined with the consistent daily SC and an extensive <strong>sales calendar</strong> (seasonal promos, purchase bonuses), new players have multiple earn paths from day one.</p>',
 steps=['Visit <a href="https://lunalandcasino.com/?inviter=9d8611a0-3ce7-5f54-a691-261bb2e300e2" target="_blank" rel="noopener">lunalandcasino.com</a> and register.','Verify your email to receive your welcome package.','Log in daily for the farmable SC bonus.','Explore the 800+ game library.','Reach $50 SC for your first cash redemption.'],
 pros=['Farmable daily SC — consistent predictable earning','$50 cash minimum — lower than most Mid Tier platforms','Great welcome package with front-loaded value','800+ game library with good variety','VIP program with tiered rewards','Delaware-regulated operation'],
 cons=['LOW daily SC amount — modest per-login earning','No gift card or crypto redemption options','Limited track record compared to established platforms','Canada not available','Medium promotional frequency','No crypto redemption'],
 games_detail='<p>LunaLand Casino offers <strong>800+ games</strong> across slots, table games, and specialty titles. The catalog covers all volatility levels for slots and provides good table game representation with blackjack, roulette, and poker variants. Regular new additions and strong mobile performance.</p>',
 bonus_detail='<p>LunaLand\'s daily SC is LOW in amount but <strong>farmable</strong> — the key distinction. Every day, a guaranteed (if modest) SC credit lands in your account. Combined with the <strong>extensive sales calendar</strong>, welcome package, and VIP tier bonuses, the total monthly earning is competitive despite the small daily base amount.</p>',
 payout_detail='<p>LunaLand Casino requires <strong>$50 SC</strong> minimum for cash redemption — one of the lower floors among Mid Tier platforms. Complete KYC identity verification in your account settings. No gift card or crypto options. Processing takes <strong>3–7 business days</strong>.</p>',
 faqs=[
  ('Is LunaLand Casino legit?','Yes. LunaLand Casino is Delaware-regulated and has been paying out players since 2023.'),
  ('What is the daily bonus at LunaLand?','A farmable daily SC bonus — low in amount but consistent and predictable each login.'),
  ('What is the minimum payout at LunaLand Casino?','$50 SC for cash redemption — lower than most competitors at $100.'),
  ('Does LunaLand have a VIP program?','Yes — an included VIP program with tiered rewards for active players.'),
  ('Does LunaLand support crypto payouts?','No. Cash redemption only at $50 minimum.'),
  ('Is LunaLand Casino available in Canada?','No. US only.'),
 ]
),

] # end CASINOS

if __name__ == '__main__':
    built = 0
    for c in CASINOS:
        html = build(c)
        path = os.path.join(BASE, f"review-{c['slug']}.html")
        with open(path, 'w', encoding='utf-8') as f:
            f.write(html)
        print(f"  OK  review-{c['slug']}.html")
        built += 1
    print(f"\nDone — {built} review pages written.")
